// Copyright (c) 2017-2025 Tencent. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package v20241204

import (
    tcerr "github.com/tencentcloud/tencentcloud-sdk-go-intl-en/tencentcloud/common/errors"
    tchttp "github.com/tencentcloud/tencentcloud-sdk-go-intl-en/tencentcloud/common/http"
    "github.com/tencentcloud/tencentcloud-sdk-go-intl-en/tencentcloud/common/json"
)

// Predefined struct for user
type CreateAlarmRequestParams struct {
	// Alarm rule name. specifies the name of the Alarm rule.
	Name *string `json:"Name,omitnil,omitempty" name:"Name"`

	// Product ID.
	ProductId *int64 `json:"ProductId,omitnil,omitempty" name:"ProductId"`

	// Quota ID.
	QuotaId *int64 `json:"QuotaId,omitnil,omitempty" name:"QuotaId"`

	// Alert metrics 1: quota usage 2: quota usage rate 3: remaining quota 4: remaining quota rate.
	Metrics *int64 `json:"Metrics,omitnil,omitempty" name:"Metrics"`

	// Specifies the Alarm threshold. value range: 0-100.
	Threshold *int64 `json:"Threshold,omitnil,omitempty" name:"Threshold"`

	// Alarm frequency.
	Frequency *int64 `json:"Frequency,omitnil,omitempty" name:"Frequency"`

	//   Member UIN
	MemberUin *int64 `json:"MemberUin,omitnil,omitempty" name:"MemberUin"`
}

type CreateAlarmRequest struct {
	*tchttp.BaseRequest
	
	// Alarm rule name. specifies the name of the Alarm rule.
	Name *string `json:"Name,omitnil,omitempty" name:"Name"`

	// Product ID.
	ProductId *int64 `json:"ProductId,omitnil,omitempty" name:"ProductId"`

	// Quota ID.
	QuotaId *int64 `json:"QuotaId,omitnil,omitempty" name:"QuotaId"`

	// Alert metrics 1: quota usage 2: quota usage rate 3: remaining quota 4: remaining quota rate.
	Metrics *int64 `json:"Metrics,omitnil,omitempty" name:"Metrics"`

	// Specifies the Alarm threshold. value range: 0-100.
	Threshold *int64 `json:"Threshold,omitnil,omitempty" name:"Threshold"`

	// Alarm frequency.
	Frequency *int64 `json:"Frequency,omitnil,omitempty" name:"Frequency"`

	//   Member UIN
	MemberUin *int64 `json:"MemberUin,omitnil,omitempty" name:"MemberUin"`
}

func (r *CreateAlarmRequest) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *CreateAlarmRequest) FromJsonString(s string) error {
	f := make(map[string]interface{})
	if err := json.Unmarshal([]byte(s), &f); err != nil {
		return err
	}
	delete(f, "Name")
	delete(f, "ProductId")
	delete(f, "QuotaId")
	delete(f, "Metrics")
	delete(f, "Threshold")
	delete(f, "Frequency")
	delete(f, "MemberUin")
	if len(f) > 0 {
		return tcerr.NewTencentCloudSDKError("ClientError.BuildRequestError", "CreateAlarmRequest has unknown keys!", "")
	}
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type CreateAlarmResponseParams struct {
	// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
	RequestId *string `json:"RequestId,omitnil,omitempty" name:"RequestId"`
}

type CreateAlarmResponse struct {
	*tchttp.BaseResponse
	Response *CreateAlarmResponseParams `json:"Response"`
}

func (r *CreateAlarmResponse) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *CreateAlarmResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}