// Copyright (c) 2017-2018 THL A29 Limited, a Tencent company. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package v20230110

import (
    tcerr "github.com/tencentcloud/tencentcloud-sdk-go-intl-en/tencentcloud/common/errors"
    tchttp "github.com/tencentcloud/tencentcloud-sdk-go-intl-en/tencentcloud/common/http"
    "github.com/tencentcloud/tencentcloud-sdk-go-intl-en/tencentcloud/common/json"
)

type BaselineConfigItem struct {
	// A unique identifier for an Account Factory baseline item, which can only contain English letters, digits, and @,._[]-:()+=. It must be 2-128 characters long.Note: This field may return null, indicating that no valid values can be obtained.
	Identifier *string `json:"Identifier,omitnil,omitempty" name:"Identifier"`

	// Account Factory baseline item configuration. Different items have different parameters.Note: This field may return null, indicating that no valid values can be obtained.
	Configuration *string `json:"Configuration,omitnil,omitempty" name:"Configuration"`
}

// Predefined struct for user
type BatchApplyAccountBaselinesRequestParams struct {
	// Member account UIN, which is also the UIN of the account to which the baseline is applied.
	MemberUinList []*int64 `json:"MemberUinList,omitnil,omitempty" name:"MemberUinList"`

	// List of baseline item configuration information.
	BaselineConfigItems []*BaselineConfigItem `json:"BaselineConfigItems,omitnil,omitempty" name:"BaselineConfigItems"`
}

type BatchApplyAccountBaselinesRequest struct {
	*tchttp.BaseRequest
	
	// Member account UIN, which is also the UIN of the account to which the baseline is applied.
	MemberUinList []*int64 `json:"MemberUinList,omitnil,omitempty" name:"MemberUinList"`

	// List of baseline item configuration information.
	BaselineConfigItems []*BaselineConfigItem `json:"BaselineConfigItems,omitnil,omitempty" name:"BaselineConfigItems"`
}

func (r *BatchApplyAccountBaselinesRequest) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *BatchApplyAccountBaselinesRequest) FromJsonString(s string) error {
	f := make(map[string]interface{})
	if err := json.Unmarshal([]byte(s), &f); err != nil {
		return err
	}
	delete(f, "MemberUinList")
	delete(f, "BaselineConfigItems")
	if len(f) > 0 {
		return tcerr.NewTencentCloudSDKError("ClientError.BuildRequestError", "BatchApplyAccountBaselinesRequest has unknown keys!", "")
	}
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type BatchApplyAccountBaselinesResponseParams struct {
	// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
	RequestId *string `json:"RequestId,omitnil,omitempty" name:"RequestId"`
}

type BatchApplyAccountBaselinesResponse struct {
	*tchttp.BaseResponse
	Response *BatchApplyAccountBaselinesResponseParams `json:"Response"`
}

func (r *BatchApplyAccountBaselinesResponse) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *BatchApplyAccountBaselinesResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}