// Copyright (c) 2017-2018 THL A29 Limited, a Tencent company. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package v20200527

import (
    tcerr "github.com/tencentcloud/tencentcloud-sdk-go-intl-en/tencentcloud/common/errors"
    tchttp "github.com/tencentcloud/tencentcloud-sdk-go-intl-en/tencentcloud/common/http"
    "github.com/tencentcloud/tencentcloud-sdk-go-intl-en/tencentcloud/common/json"
)

type AliasValueConf struct {
	// Alias.
	Alias *string `json:"Alias,omitnil,omitempty" name:"Alias"`

	// Value.
	Value *string `json:"Value,omitnil,omitempty" name:"Value"`
}

// Predefined struct for user
type BindNewLVBDomainWithChannelRequestParams struct {
	// Channel ID
	ChannelId *string `json:"ChannelId,omitnil,omitempty" name:"ChannelId"`

	// The LVB domain name to bind
	LVBDomain *string `json:"LVBDomain,omitnil,omitempty" name:"LVBDomain"`
}

type BindNewLVBDomainWithChannelRequest struct {
	*tchttp.BaseRequest
	
	// Channel ID
	ChannelId *string `json:"ChannelId,omitnil,omitempty" name:"ChannelId"`

	// The LVB domain name to bind
	LVBDomain *string `json:"LVBDomain,omitnil,omitempty" name:"LVBDomain"`
}

func (r *BindNewLVBDomainWithChannelRequest) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *BindNewLVBDomainWithChannelRequest) FromJsonString(s string) error {
	f := make(map[string]interface{})
	if err := json.Unmarshal([]byte(s), &f); err != nil {
		return err
	}
	delete(f, "ChannelId")
	delete(f, "LVBDomain")
	if len(f) > 0 {
		return tcerr.NewTencentCloudSDKError("ClientError.BuildRequestError", "BindNewLVBDomainWithChannelRequest has unknown keys!", "")
	}
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type BindNewLVBDomainWithChannelResponseParams struct {
	// The LVB domain name bound successfully
	LVBDomain *string `json:"LVBDomain,omitnil,omitempty" name:"LVBDomain"`

	// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
	RequestId *string `json:"RequestId,omitnil,omitempty" name:"RequestId"`
}

type BindNewLVBDomainWithChannelResponse struct {
	*tchttp.BaseResponse
	Response *BindNewLVBDomainWithChannelResponseParams `json:"Response"`
}

func (r *BindNewLVBDomainWithChannelResponse) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *BindNewLVBDomainWithChannelResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

type CacheInfo struct {
	// List of timeout parameter configuration
	// Note: this field may return `null`, indicating that no valid value was found.
	Info []*CacheInfoInfo `json:"Info,omitnil,omitempty" name:"Info"`
}

type CacheInfoInfo struct {
	// Timeout period (ms), which must be an integer multiple of 1000
	// .m3u8/.mpd: [1000, 60000]
	// .ts/.m4s/.mp4: [10000, 1800000]
	Timeout *int64 `json:"Timeout,omitnil,omitempty" name:"Timeout"`

	// File extension. Valid values: .m3u8, .ts, .mpd, .m4s, .mp4
	// Note: this field may return `null`, indicating that no valid value was found.
	Ext *string `json:"Ext,omitnil,omitempty" name:"Ext"`
}

type ChannelInfo struct {
	// Channel ID.
	Id *string `json:"Id,omitnil,omitempty" name:"Id"`

	// Channel name.
	Name *string `json:"Name,omitnil,omitempty" name:"Name"`

	// Channel protocol.
	Protocol *string `json:"Protocol,omitnil,omitempty" name:"Protocol"`

	// Channel input and output.
	Points *PointInfo `json:"Points,omitnil,omitempty" name:"Points"`

	// Cache configuration
	// Note: this field may return `null`, indicating that no valid value was found.
	CacheInfo *CacheInfo `json:"CacheInfo,omitnil,omitempty" name:"CacheInfo"`
}

type ConfigAliasesInfo struct {
	// parameter name.
	ParamName *string `json:"ParamName,omitnil,omitempty" name:"ParamName"`

	// Alias-value configuration.
	AliasValueList []*AliasValueConf `json:"AliasValueList,omitnil,omitempty" name:"AliasValueList"`
}

// Predefined struct for user
type CreateStreamPackageChannelEndpointRequestParams struct {
	// Channel ID
	Id *string `json:"Id,omitnil,omitempty" name:"Id"`

	// Endpoint name, which must contain 1 to 32 characters and supports digits, letters, and underscores
	Name *string `json:"Name,omitnil,omitempty" name:"Name"`

	// Authentication information
	AuthInfo *EndpointAuthInfo `json:"AuthInfo,omitnil,omitempty" name:"AuthInfo"`

	// Endpoint protocol type, supports HLS, DASH, CMAF (only HLS type input can create CMAF Endpoint).
	Protocol *string `json:"Protocol,omitnil,omitempty" name:"Protocol"`

	// Mainifest name, default is main.
	Manifest *string `json:"Manifest,omitnil,omitempty" name:"Manifest"`

	// Whether to turn on the TimeShift function, true: on, false: off, the default is off.
	TimeShiftEnable *bool `json:"TimeShiftEnable,omitnil,omitempty" name:"TimeShiftEnable"`

	// The number of days to look back in TimeShift, up to 30 days is supported.
	TimeShiftDuration *uint64 `json:"TimeShiftDuration,omitnil,omitempty" name:"TimeShiftDuration"`
}

type CreateStreamPackageChannelEndpointRequest struct {
	*tchttp.BaseRequest
	
	// Channel ID
	Id *string `json:"Id,omitnil,omitempty" name:"Id"`

	// Endpoint name, which must contain 1 to 32 characters and supports digits, letters, and underscores
	Name *string `json:"Name,omitnil,omitempty" name:"Name"`

	// Authentication information
	AuthInfo *EndpointAuthInfo `json:"AuthInfo,omitnil,omitempty" name:"AuthInfo"`

	// Endpoint protocol type, supports HLS, DASH, CMAF (only HLS type input can create CMAF Endpoint).
	Protocol *string `json:"Protocol,omitnil,omitempty" name:"Protocol"`

	// Mainifest name, default is main.
	Manifest *string `json:"Manifest,omitnil,omitempty" name:"Manifest"`

	// Whether to turn on the TimeShift function, true: on, false: off, the default is off.
	TimeShiftEnable *bool `json:"TimeShiftEnable,omitnil,omitempty" name:"TimeShiftEnable"`

	// The number of days to look back in TimeShift, up to 30 days is supported.
	TimeShiftDuration *uint64 `json:"TimeShiftDuration,omitnil,omitempty" name:"TimeShiftDuration"`
}

func (r *CreateStreamPackageChannelEndpointRequest) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *CreateStreamPackageChannelEndpointRequest) FromJsonString(s string) error {
	f := make(map[string]interface{})
	if err := json.Unmarshal([]byte(s), &f); err != nil {
		return err
	}
	delete(f, "Id")
	delete(f, "Name")
	delete(f, "AuthInfo")
	delete(f, "Protocol")
	delete(f, "Manifest")
	delete(f, "TimeShiftEnable")
	delete(f, "TimeShiftDuration")
	if len(f) > 0 {
		return tcerr.NewTencentCloudSDKError("ClientError.BuildRequestError", "CreateStreamPackageChannelEndpointRequest has unknown keys!", "")
	}
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type CreateStreamPackageChannelEndpointResponseParams struct {
	// Information of the created channel endpoint
	Info *EndpointInfo `json:"Info,omitnil,omitempty" name:"Info"`

	// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
	RequestId *string `json:"RequestId,omitnil,omitempty" name:"RequestId"`
}

type CreateStreamPackageChannelEndpointResponse struct {
	*tchttp.BaseResponse
	Response *CreateStreamPackageChannelEndpointResponseParams `json:"Response"`
}

func (r *CreateStreamPackageChannelEndpointResponse) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *CreateStreamPackageChannelEndpointResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type CreateStreamPackageChannelRequestParams struct {
	// Channel name
	Name *string `json:"Name,omitnil,omitempty" name:"Name"`

	// Channel protocol. Valid values: HLS, DASH
	Protocol *string `json:"Protocol,omitnil,omitempty" name:"Protocol"`

	// Cache configuration
	CacheInfo *CacheInfo `json:"CacheInfo,omitnil,omitempty" name:"CacheInfo"`
}

type CreateStreamPackageChannelRequest struct {
	*tchttp.BaseRequest
	
	// Channel name
	Name *string `json:"Name,omitnil,omitempty" name:"Name"`

	// Channel protocol. Valid values: HLS, DASH
	Protocol *string `json:"Protocol,omitnil,omitempty" name:"Protocol"`

	// Cache configuration
	CacheInfo *CacheInfo `json:"CacheInfo,omitnil,omitempty" name:"CacheInfo"`
}

func (r *CreateStreamPackageChannelRequest) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *CreateStreamPackageChannelRequest) FromJsonString(s string) error {
	f := make(map[string]interface{})
	if err := json.Unmarshal([]byte(s), &f); err != nil {
		return err
	}
	delete(f, "Name")
	delete(f, "Protocol")
	delete(f, "CacheInfo")
	if len(f) > 0 {
		return tcerr.NewTencentCloudSDKError("ClientError.BuildRequestError", "CreateStreamPackageChannelRequest has unknown keys!", "")
	}
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type CreateStreamPackageChannelResponseParams struct {
	// Channel information
	Info *ChannelInfo `json:"Info,omitnil,omitempty" name:"Info"`

	// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
	RequestId *string `json:"RequestId,omitnil,omitempty" name:"RequestId"`
}

type CreateStreamPackageChannelResponse struct {
	*tchttp.BaseResponse
	Response *CreateStreamPackageChannelResponseParams `json:"Response"`
}

func (r *CreateStreamPackageChannelResponse) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *CreateStreamPackageChannelResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type CreateStreamPackageHarvestJobRequestParams struct {
	// HarvestJob ID, a globally unique identifier.
	ID *string `json:"ID,omitnil,omitempty" name:"ID"`

	// The associated channel name.
	ChannelName *string `json:"ChannelName,omitnil,omitempty" name:"ChannelName"`

	// The associated endpoint name.
	EndpointName *string `json:"EndpointName,omitnil,omitempty" name:"EndpointName"`

	// Time format, supports the following types: 1. Epoch seconds 2. ISO-8601
	TimeFormat *string `json:"TimeFormat,omitnil,omitempty" name:"TimeFormat"`

	// Task start time supports two formats for TimeFormat input: 1. Epoch seconds: The input box is a numeric input box, and only positive integers can be entered. 2. ISO-8601: The supported format is ISO time, for example: 2023-08-01T10:00:00+08:00.
	StartTime *string `json:"StartTime,omitnil,omitempty" name:"StartTime"`

	// Task end time supports two formats for TimeFormat input: 1. Epoch seconds: The input box is a numeric input box, and only positive integers can be entered. 2. ISO-8601: The supported format is ISO time, for example: 2023-08-01T10:00:00+08:00.
	EndTime *string `json:"EndTime,omitnil,omitempty" name:"EndTime"`

	// The path where the recording file is stored in Cos.
	Destination *string `json:"Destination,omitnil,omitempty" name:"Destination"`

	// The file name of the recording file stored in Cos.
	Manifest *string `json:"Manifest,omitnil,omitempty" name:"Manifest"`
}

type CreateStreamPackageHarvestJobRequest struct {
	*tchttp.BaseRequest
	
	// HarvestJob ID, a globally unique identifier.
	ID *string `json:"ID,omitnil,omitempty" name:"ID"`

	// The associated channel name.
	ChannelName *string `json:"ChannelName,omitnil,omitempty" name:"ChannelName"`

	// The associated endpoint name.
	EndpointName *string `json:"EndpointName,omitnil,omitempty" name:"EndpointName"`

	// Time format, supports the following types: 1. Epoch seconds 2. ISO-8601
	TimeFormat *string `json:"TimeFormat,omitnil,omitempty" name:"TimeFormat"`

	// Task start time supports two formats for TimeFormat input: 1. Epoch seconds: The input box is a numeric input box, and only positive integers can be entered. 2. ISO-8601: The supported format is ISO time, for example: 2023-08-01T10:00:00+08:00.
	StartTime *string `json:"StartTime,omitnil,omitempty" name:"StartTime"`

	// Task end time supports two formats for TimeFormat input: 1. Epoch seconds: The input box is a numeric input box, and only positive integers can be entered. 2. ISO-8601: The supported format is ISO time, for example: 2023-08-01T10:00:00+08:00.
	EndTime *string `json:"EndTime,omitnil,omitempty" name:"EndTime"`

	// The path where the recording file is stored in Cos.
	Destination *string `json:"Destination,omitnil,omitempty" name:"Destination"`

	// The file name of the recording file stored in Cos.
	Manifest *string `json:"Manifest,omitnil,omitempty" name:"Manifest"`
}

func (r *CreateStreamPackageHarvestJobRequest) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *CreateStreamPackageHarvestJobRequest) FromJsonString(s string) error {
	f := make(map[string]interface{})
	if err := json.Unmarshal([]byte(s), &f); err != nil {
		return err
	}
	delete(f, "ID")
	delete(f, "ChannelName")
	delete(f, "EndpointName")
	delete(f, "TimeFormat")
	delete(f, "StartTime")
	delete(f, "EndTime")
	delete(f, "Destination")
	delete(f, "Manifest")
	if len(f) > 0 {
		return tcerr.NewTencentCloudSDKError("ClientError.BuildRequestError", "CreateStreamPackageHarvestJobRequest has unknown keys!", "")
	}
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type CreateStreamPackageHarvestJobResponseParams struct {
	// HarvestJob information.
	Info *HarvestJobResp `json:"Info,omitnil,omitempty" name:"Info"`

	// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
	RequestId *string `json:"RequestId,omitnil,omitempty" name:"RequestId"`
}

type CreateStreamPackageHarvestJobResponse struct {
	*tchttp.BaseResponse
	Response *CreateStreamPackageHarvestJobResponseParams `json:"Response"`
}

func (r *CreateStreamPackageHarvestJobResponse) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *CreateStreamPackageHarvestJobResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type DeleteStreamPackageChannelEndpointsRequestParams struct {
	// Channel ID
	Id *string `json:"Id,omitnil,omitempty" name:"Id"`

	// List of the URLs of the endpoints to delete
	Urls []*string `json:"Urls,omitnil,omitempty" name:"Urls"`
}

type DeleteStreamPackageChannelEndpointsRequest struct {
	*tchttp.BaseRequest
	
	// Channel ID
	Id *string `json:"Id,omitnil,omitempty" name:"Id"`

	// List of the URLs of the endpoints to delete
	Urls []*string `json:"Urls,omitnil,omitempty" name:"Urls"`
}

func (r *DeleteStreamPackageChannelEndpointsRequest) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *DeleteStreamPackageChannelEndpointsRequest) FromJsonString(s string) error {
	f := make(map[string]interface{})
	if err := json.Unmarshal([]byte(s), &f); err != nil {
		return err
	}
	delete(f, "Id")
	delete(f, "Urls")
	if len(f) > 0 {
		return tcerr.NewTencentCloudSDKError("ClientError.BuildRequestError", "DeleteStreamPackageChannelEndpointsRequest has unknown keys!", "")
	}
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type DeleteStreamPackageChannelEndpointsResponseParams struct {
	// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
	RequestId *string `json:"RequestId,omitnil,omitempty" name:"RequestId"`
}

type DeleteStreamPackageChannelEndpointsResponse struct {
	*tchttp.BaseResponse
	Response *DeleteStreamPackageChannelEndpointsResponseParams `json:"Response"`
}

func (r *DeleteStreamPackageChannelEndpointsResponse) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *DeleteStreamPackageChannelEndpointsResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type DeleteStreamPackageChannelsRequestParams struct {
	// List of the IDs of the channels to delete
	Ids []*string `json:"Ids,omitnil,omitempty" name:"Ids"`
}

type DeleteStreamPackageChannelsRequest struct {
	*tchttp.BaseRequest
	
	// List of the IDs of the channels to delete
	Ids []*string `json:"Ids,omitnil,omitempty" name:"Ids"`
}

func (r *DeleteStreamPackageChannelsRequest) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *DeleteStreamPackageChannelsRequest) FromJsonString(s string) error {
	f := make(map[string]interface{})
	if err := json.Unmarshal([]byte(s), &f); err != nil {
		return err
	}
	delete(f, "Ids")
	if len(f) > 0 {
		return tcerr.NewTencentCloudSDKError("ClientError.BuildRequestError", "DeleteStreamPackageChannelsRequest has unknown keys!", "")
	}
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type DeleteStreamPackageChannelsResponseParams struct {
	// List of the information of successfully deleted channels
	SuccessInfos []*ChannelInfo `json:"SuccessInfos,omitnil,omitempty" name:"SuccessInfos"`

	// List of the information of the channels that failed to be deleted
	FailInfos []*ChannelInfo `json:"FailInfos,omitnil,omitempty" name:"FailInfos"`

	// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
	RequestId *string `json:"RequestId,omitnil,omitempty" name:"RequestId"`
}

type DeleteStreamPackageChannelsResponse struct {
	*tchttp.BaseResponse
	Response *DeleteStreamPackageChannelsResponseParams `json:"Response"`
}

func (r *DeleteStreamPackageChannelsResponse) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *DeleteStreamPackageChannelsResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type DeleteStreamPackageHarvestJobRequestParams struct {
	// HarvestJob ID, a globally unique identifier.
	ID *string `json:"ID,omitnil,omitempty" name:"ID"`
}

type DeleteStreamPackageHarvestJobRequest struct {
	*tchttp.BaseRequest
	
	// HarvestJob ID, a globally unique identifier.
	ID *string `json:"ID,omitnil,omitempty" name:"ID"`
}

func (r *DeleteStreamPackageHarvestJobRequest) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *DeleteStreamPackageHarvestJobRequest) FromJsonString(s string) error {
	f := make(map[string]interface{})
	if err := json.Unmarshal([]byte(s), &f); err != nil {
		return err
	}
	delete(f, "ID")
	if len(f) > 0 {
		return tcerr.NewTencentCloudSDKError("ClientError.BuildRequestError", "DeleteStreamPackageHarvestJobRequest has unknown keys!", "")
	}
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type DeleteStreamPackageHarvestJobResponseParams struct {
	// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
	RequestId *string `json:"RequestId,omitnil,omitempty" name:"RequestId"`
}

type DeleteStreamPackageHarvestJobResponse struct {
	*tchttp.BaseResponse
	Response *DeleteStreamPackageHarvestJobResponseParams `json:"Response"`
}

func (r *DeleteStreamPackageHarvestJobResponse) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *DeleteStreamPackageHarvestJobResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type DeleteStreamPackageHarvestJobsRequestParams struct {
	// HarvestJob IDs, id is a globally unique identifier.
	IDs []*string `json:"IDs,omitnil,omitempty" name:"IDs"`
}

type DeleteStreamPackageHarvestJobsRequest struct {
	*tchttp.BaseRequest
	
	// HarvestJob IDs, id is a globally unique identifier.
	IDs []*string `json:"IDs,omitnil,omitempty" name:"IDs"`
}

func (r *DeleteStreamPackageHarvestJobsRequest) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *DeleteStreamPackageHarvestJobsRequest) FromJsonString(s string) error {
	f := make(map[string]interface{})
	if err := json.Unmarshal([]byte(s), &f); err != nil {
		return err
	}
	delete(f, "IDs")
	if len(f) > 0 {
		return tcerr.NewTencentCloudSDKError("ClientError.BuildRequestError", "DeleteStreamPackageHarvestJobsRequest has unknown keys!", "")
	}
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type DeleteStreamPackageHarvestJobsResponseParams struct {
	// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
	RequestId *string `json:"RequestId,omitnil,omitempty" name:"RequestId"`
}

type DeleteStreamPackageHarvestJobsResponse struct {
	*tchttp.BaseResponse
	Response *DeleteStreamPackageHarvestJobsResponseParams `json:"Response"`
}

func (r *DeleteStreamPackageHarvestJobsResponse) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *DeleteStreamPackageHarvestJobsResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type DescribeStreamPackageChannelRequestParams struct {
	// Channel ID
	Id *string `json:"Id,omitnil,omitempty" name:"Id"`
}

type DescribeStreamPackageChannelRequest struct {
	*tchttp.BaseRequest
	
	// Channel ID
	Id *string `json:"Id,omitnil,omitempty" name:"Id"`
}

func (r *DescribeStreamPackageChannelRequest) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *DescribeStreamPackageChannelRequest) FromJsonString(s string) error {
	f := make(map[string]interface{})
	if err := json.Unmarshal([]byte(s), &f); err != nil {
		return err
	}
	delete(f, "Id")
	if len(f) > 0 {
		return tcerr.NewTencentCloudSDKError("ClientError.BuildRequestError", "DescribeStreamPackageChannelRequest has unknown keys!", "")
	}
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type DescribeStreamPackageChannelResponseParams struct {
	// Channel information
	Info *ChannelInfo `json:"Info,omitnil,omitempty" name:"Info"`

	// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
	RequestId *string `json:"RequestId,omitnil,omitempty" name:"RequestId"`
}

type DescribeStreamPackageChannelResponse struct {
	*tchttp.BaseResponse
	Response *DescribeStreamPackageChannelResponseParams `json:"Response"`
}

func (r *DescribeStreamPackageChannelResponse) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *DescribeStreamPackageChannelResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type DescribeStreamPackageChannelsRequestParams struct {
	// Page number. Value range: [1, 1000]
	PageNum *uint64 `json:"PageNum,omitnil,omitempty" name:"PageNum"`

	// Number of entries per page. Value range: [1, 1000]
	PageSize *uint64 `json:"PageSize,omitnil,omitempty" name:"PageSize"`
}

type DescribeStreamPackageChannelsRequest struct {
	*tchttp.BaseRequest
	
	// Page number. Value range: [1, 1000]
	PageNum *uint64 `json:"PageNum,omitnil,omitempty" name:"PageNum"`

	// Number of entries per page. Value range: [1, 1000]
	PageSize *uint64 `json:"PageSize,omitnil,omitempty" name:"PageSize"`
}

func (r *DescribeStreamPackageChannelsRequest) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *DescribeStreamPackageChannelsRequest) FromJsonString(s string) error {
	f := make(map[string]interface{})
	if err := json.Unmarshal([]byte(s), &f); err != nil {
		return err
	}
	delete(f, "PageNum")
	delete(f, "PageSize")
	if len(f) > 0 {
		return tcerr.NewTencentCloudSDKError("ClientError.BuildRequestError", "DescribeStreamPackageChannelsRequest has unknown keys!", "")
	}
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type DescribeStreamPackageChannelsResponseParams struct {
	// List of channel information
	// Note: this field may return `null`, indicating that no valid value was found.
	Infos []*ChannelInfo `json:"Infos,omitnil,omitempty" name:"Infos"`

	// Page number
	PageNum *uint64 `json:"PageNum,omitnil,omitempty" name:"PageNum"`

	// Number of entries per page
	PageSize *uint64 `json:"PageSize,omitnil,omitempty" name:"PageSize"`

	// Total number of entries
	TotalNum *uint64 `json:"TotalNum,omitnil,omitempty" name:"TotalNum"`

	// Total number of pages
	TotalPage *uint64 `json:"TotalPage,omitnil,omitempty" name:"TotalPage"`

	// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
	RequestId *string `json:"RequestId,omitnil,omitempty" name:"RequestId"`
}

type DescribeStreamPackageChannelsResponse struct {
	*tchttp.BaseResponse
	Response *DescribeStreamPackageChannelsResponseParams `json:"Response"`
}

func (r *DescribeStreamPackageChannelsResponse) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *DescribeStreamPackageChannelsResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type DescribeStreamPackageHarvestJobRequestParams struct {
	// HarvestJob ID, a globally unique identifier.
	ID *string `json:"ID,omitnil,omitempty" name:"ID"`
}

type DescribeStreamPackageHarvestJobRequest struct {
	*tchttp.BaseRequest
	
	// HarvestJob ID, a globally unique identifier.
	ID *string `json:"ID,omitnil,omitempty" name:"ID"`
}

func (r *DescribeStreamPackageHarvestJobRequest) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *DescribeStreamPackageHarvestJobRequest) FromJsonString(s string) error {
	f := make(map[string]interface{})
	if err := json.Unmarshal([]byte(s), &f); err != nil {
		return err
	}
	delete(f, "ID")
	if len(f) > 0 {
		return tcerr.NewTencentCloudSDKError("ClientError.BuildRequestError", "DescribeStreamPackageHarvestJobRequest has unknown keys!", "")
	}
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type DescribeStreamPackageHarvestJobResponseParams struct {
	// HarvestJob information.
	Info *HarvestJobResp `json:"Info,omitnil,omitempty" name:"Info"`

	// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
	RequestId *string `json:"RequestId,omitnil,omitempty" name:"RequestId"`
}

type DescribeStreamPackageHarvestJobResponse struct {
	*tchttp.BaseResponse
	Response *DescribeStreamPackageHarvestJobResponseParams `json:"Response"`
}

func (r *DescribeStreamPackageHarvestJobResponse) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *DescribeStreamPackageHarvestJobResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type DescribeStreamPackageHarvestJobsRequestParams struct {
	// The bound channel name. If not passed, all channels will be queried by default.
	ChannelName *string `json:"ChannelName,omitnil,omitempty" name:"ChannelName"`

	// Page number.
	PageNum *uint64 `json:"PageNum,omitnil,omitempty" name:"PageNum"`

	// PageSize.
	PageSize *uint64 `json:"PageSize,omitnil,omitempty" name:"PageSize"`
}

type DescribeStreamPackageHarvestJobsRequest struct {
	*tchttp.BaseRequest
	
	// The bound channel name. If not passed, all channels will be queried by default.
	ChannelName *string `json:"ChannelName,omitnil,omitempty" name:"ChannelName"`

	// Page number.
	PageNum *uint64 `json:"PageNum,omitnil,omitempty" name:"PageNum"`

	// PageSize.
	PageSize *uint64 `json:"PageSize,omitnil,omitempty" name:"PageSize"`
}

func (r *DescribeStreamPackageHarvestJobsRequest) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *DescribeStreamPackageHarvestJobsRequest) FromJsonString(s string) error {
	f := make(map[string]interface{})
	if err := json.Unmarshal([]byte(s), &f); err != nil {
		return err
	}
	delete(f, "ChannelName")
	delete(f, "PageNum")
	delete(f, "PageSize")
	if len(f) > 0 {
		return tcerr.NewTencentCloudSDKError("ClientError.BuildRequestError", "DescribeStreamPackageHarvestJobsRequest has unknown keys!", "")
	}
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type DescribeStreamPackageHarvestJobsResponseParams struct {
	// HarvestJob information list.
	Infos []*HarvestJobResp `json:"Infos,omitnil,omitempty" name:"Infos"`

	// Page number.
	PageNum *uint64 `json:"PageNum,omitnil,omitempty" name:"PageNum"`

	// PageSize
	PageSize *uint64 `json:"PageSize,omitnil,omitempty" name:"PageSize"`

	// TotalNum
	TotalNum *uint64 `json:"TotalNum,omitnil,omitempty" name:"TotalNum"`

	// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
	RequestId *string `json:"RequestId,omitnil,omitempty" name:"RequestId"`
}

type DescribeStreamPackageHarvestJobsResponse struct {
	*tchttp.BaseResponse
	Response *DescribeStreamPackageHarvestJobsResponseParams `json:"Response"`
}

func (r *DescribeStreamPackageHarvestJobsResponse) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *DescribeStreamPackageHarvestJobsResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

type EndpointAuthInfo struct {
	// The security group allowlist in CIDR format.
	// Note: this field may return null, indicating that no valid values can be obtained.
	WhiteIpList []*string `json:"WhiteIpList,omitnil,omitempty" name:"WhiteIpList"`

	// The security group blocklist in CIDR format.
	// Note: this field may return null, indicating that no valid values can be obtained.
	BlackIpList []*string `json:"BlackIpList,omitnil,omitempty" name:"BlackIpList"`

	// The authentication key. Its value is same as `X-TENCENT-PACKAGE` set in the HTTP request header.
	// Note: this field may return null, indicating that no valid values can be obtained.
	AuthKey *string `json:"AuthKey,omitnil,omitempty" name:"AuthKey"`
}

type EndpointInfo struct {
	// Endpoint name.
	Name *string `json:"Name,omitnil,omitempty" name:"Name"`

	// Endpoint URL.
	Url *string `json:"Url,omitnil,omitempty" name:"Url"`

	// Endpoint authentication information.
	AuthInfo *EndpointAuthInfo `json:"AuthInfo,omitnil,omitempty" name:"AuthInfo"`

	// Endpoint protocol.
	Protocol *string `json:"Protocol,omitnil,omitempty" name:"Protocol"`

	// Manifest name, default is main.
	Manifest *string `json:"Manifest,omitnil,omitempty" name:"Manifest"`

	// Whether to turn on the time shift function, true: on, false: off, the default is off.
	TimeShiftEnable *bool `json:"TimeShiftEnable,omitnil,omitempty" name:"TimeShiftEnable"`

	// The number of days in the time shift window, up to 30 days. Valid when TimeShiftEnable is turned on.
	TimeShiftDuration *uint64 `json:"TimeShiftDuration,omitnil,omitempty" name:"TimeShiftDuration"`

	// Advertising insertion function switch.
	SSAIEnable *bool `json:"SSAIEnable,omitnil,omitempty" name:"SSAIEnable"`

	// Ad insertion function configuration information.
	SSAIInfo *SSAIConf `json:"SSAIInfo,omitnil,omitempty" name:"SSAIInfo"`

	// The customer-defined url parameter is inserted into the subscript at the specified position of the Endpoint url. The optional range of the subscript is: [0,3].
	CustomUrlParamIndex *uint64 `json:"CustomUrlParamIndex,omitnil,omitempty" name:"CustomUrlParamIndex"`

	// Customer-defined url parameters are inserted into the specified position of the Endpoint url based on the CustomUrlParamIndex.
	// The parameters can only contain digits, letters, underscores (_), and hyphens (-), with a length of 1 to 64 chars.
	CustomUrlParam *string `json:"CustomUrlParam,omitnil,omitempty" name:"CustomUrlParam"`
}

type HarvestJobResp struct {
	// HarvestJob ID, a globally unique identifier.
	ID *string `json:"ID,omitnil,omitempty" name:"ID"`

	// The associated channel name.
	ChannelName *string `json:"ChannelName,omitnil,omitempty" name:"ChannelName"`

	// The associated endpoint name.
	EndpointName *string `json:"EndpointName,omitnil,omitempty" name:"EndpointName"`

	// Time format, supports the following types: 1. Epoch seconds 2. ISO-8601
	TimeFormat *string `json:"TimeFormat,omitnil,omitempty" name:"TimeFormat"`

	// HarvestJob start time.
	StartTime *string `json:"StartTime,omitnil,omitempty" name:"StartTime"`

	// HarvestJob end time.
	EndTime *string `json:"EndTime,omitnil,omitempty" name:"EndTime"`

	// The path where the recording file is stored in COS.
	Destination *string `json:"Destination,omitnil,omitempty" name:"Destination"`

	// The file name of the recording file stored in COS.
	Manifest *string `json:"Manifest,omitnil,omitempty" name:"Manifest"`

	// The task status is divided into running: Running, execution completed: Completed, and execution failure: Failed.
	Status *string `json:"Status,omitnil,omitempty" name:"Status"`

	// HarvestJob error message.
	ErrMessage *string `json:"ErrMessage,omitnil,omitempty" name:"ErrMessage"`

	// HarvestJob creation time, timestamp in seconds.
	CreateTime *uint64 `json:"CreateTime,omitnil,omitempty" name:"CreateTime"`

	// The associated ChannelID.
	ChannelId *string `json:"ChannelId,omitnil,omitempty" name:"ChannelId"`

	// The region corresponding to the harvest job.
	Region *string `json:"Region,omitnil,omitempty" name:"Region"`
}

type InputAuthInfo struct {
	// Username.
	// Note: this field may return null, indicating that no valid values can be obtained.
	Username *string `json:"Username,omitnil,omitempty" name:"Username"`

	// Password.
	// Note: this field may return null, indicating that no valid values can be obtained.
	Password *string `json:"Password,omitnil,omitempty" name:"Password"`
}

type InputInfo struct {
	// Channel input URL.
	// Note: this field may return null, indicating that no valid values can be obtained.
	Url *string `json:"Url,omitnil,omitempty" name:"Url"`

	// Channel input authentication information.
	AuthInfo *InputAuthInfo `json:"AuthInfo,omitnil,omitempty" name:"AuthInfo"`
}

// Predefined struct for user
type ModifyStreamPackageChannelEndpointRequestParams struct {
	// Channel ID
	Id *string `json:"Id,omitnil,omitempty" name:"Id"`

	// Channel endpoint URL
	Url *string `json:"Url,omitnil,omitempty" name:"Url"`

	// New endpoint name
	Name *string `json:"Name,omitnil,omitempty" name:"Name"`

	// New channel authentication information
	AuthInfo *EndpointAuthInfo `json:"AuthInfo,omitnil,omitempty" name:"AuthInfo"`

	// Endpoint protocol.
	Protocol *string `json:"Protocol,omitnil,omitempty" name:"Protocol"`

	// Whether to turn on the time shift function, true: on, false: off, the default is off.
	TimeShiftEnable *bool `json:"TimeShiftEnable,omitnil,omitempty" name:"TimeShiftEnable"`

	// The number of days in the time shift window, up to 30 days. Valid when TimeShiftEnable is turned on.
	TimeShiftDuration *uint64 `json:"TimeShiftDuration,omitnil,omitempty" name:"TimeShiftDuration"`

	// Advertising insertion function switch.
	SSAIEnable *bool `json:"SSAIEnable,omitnil,omitempty" name:"SSAIEnable"`

	// Ad insertion function configuration information. Valid when SSAIEnable is turned on.
	SSAIInfo *SSAIConf `json:"SSAIInfo,omitnil,omitempty" name:"SSAIInfo"`

	// The customer-defined url parameter is inserted into the subscript at the specified position of the Endpoint url. 
	// Calculation starts from the first '/' in the url path, and the subscript starts from 0, the optional range of the subscript is: [0,3].
	CustomUrlParamIndex *uint64 `json:"CustomUrlParamIndex,omitnil,omitempty" name:"CustomUrlParamIndex"`

	// Customer-defined url parameters are inserted into the specified position of the Endpoint url based on the CustomUrlParamIndex.
	// The parameters can only contain digits, letters, underscores (_), and hyphens (-), with a length of 1 to 64 chars.
	CustomUrlParam *string `json:"CustomUrlParam,omitnil,omitempty" name:"CustomUrlParam"`
}

type ModifyStreamPackageChannelEndpointRequest struct {
	*tchttp.BaseRequest
	
	// Channel ID
	Id *string `json:"Id,omitnil,omitempty" name:"Id"`

	// Channel endpoint URL
	Url *string `json:"Url,omitnil,omitempty" name:"Url"`

	// New endpoint name
	Name *string `json:"Name,omitnil,omitempty" name:"Name"`

	// New channel authentication information
	AuthInfo *EndpointAuthInfo `json:"AuthInfo,omitnil,omitempty" name:"AuthInfo"`

	// Endpoint protocol.
	Protocol *string `json:"Protocol,omitnil,omitempty" name:"Protocol"`

	// Whether to turn on the time shift function, true: on, false: off, the default is off.
	TimeShiftEnable *bool `json:"TimeShiftEnable,omitnil,omitempty" name:"TimeShiftEnable"`

	// The number of days in the time shift window, up to 30 days. Valid when TimeShiftEnable is turned on.
	TimeShiftDuration *uint64 `json:"TimeShiftDuration,omitnil,omitempty" name:"TimeShiftDuration"`

	// Advertising insertion function switch.
	SSAIEnable *bool `json:"SSAIEnable,omitnil,omitempty" name:"SSAIEnable"`

	// Ad insertion function configuration information. Valid when SSAIEnable is turned on.
	SSAIInfo *SSAIConf `json:"SSAIInfo,omitnil,omitempty" name:"SSAIInfo"`

	// The customer-defined url parameter is inserted into the subscript at the specified position of the Endpoint url. 
	// Calculation starts from the first '/' in the url path, and the subscript starts from 0, the optional range of the subscript is: [0,3].
	CustomUrlParamIndex *uint64 `json:"CustomUrlParamIndex,omitnil,omitempty" name:"CustomUrlParamIndex"`

	// Customer-defined url parameters are inserted into the specified position of the Endpoint url based on the CustomUrlParamIndex.
	// The parameters can only contain digits, letters, underscores (_), and hyphens (-), with a length of 1 to 64 chars.
	CustomUrlParam *string `json:"CustomUrlParam,omitnil,omitempty" name:"CustomUrlParam"`
}

func (r *ModifyStreamPackageChannelEndpointRequest) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *ModifyStreamPackageChannelEndpointRequest) FromJsonString(s string) error {
	f := make(map[string]interface{})
	if err := json.Unmarshal([]byte(s), &f); err != nil {
		return err
	}
	delete(f, "Id")
	delete(f, "Url")
	delete(f, "Name")
	delete(f, "AuthInfo")
	delete(f, "Protocol")
	delete(f, "TimeShiftEnable")
	delete(f, "TimeShiftDuration")
	delete(f, "SSAIEnable")
	delete(f, "SSAIInfo")
	delete(f, "CustomUrlParamIndex")
	delete(f, "CustomUrlParam")
	if len(f) > 0 {
		return tcerr.NewTencentCloudSDKError("ClientError.BuildRequestError", "ModifyStreamPackageChannelEndpointRequest has unknown keys!", "")
	}
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type ModifyStreamPackageChannelEndpointResponseParams struct {
	// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
	RequestId *string `json:"RequestId,omitnil,omitempty" name:"RequestId"`
}

type ModifyStreamPackageChannelEndpointResponse struct {
	*tchttp.BaseResponse
	Response *ModifyStreamPackageChannelEndpointResponseParams `json:"Response"`
}

func (r *ModifyStreamPackageChannelEndpointResponse) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *ModifyStreamPackageChannelEndpointResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type ModifyStreamPackageChannelInputAuthInfoRequestParams struct {
	// Channel ID
	Id *string `json:"Id,omitnil,omitempty" name:"Id"`

	// Channel input URL
	Url *string `json:"Url,omitnil,omitempty" name:"Url"`

	// Authentication configuration. Valid values: `CLOSE`, `UPDATE`
	// `CLOSE`: disable authentication
	// `UPDATE`: update authentication information
	ActionType *string `json:"ActionType,omitnil,omitempty" name:"ActionType"`
}

type ModifyStreamPackageChannelInputAuthInfoRequest struct {
	*tchttp.BaseRequest
	
	// Channel ID
	Id *string `json:"Id,omitnil,omitempty" name:"Id"`

	// Channel input URL
	Url *string `json:"Url,omitnil,omitempty" name:"Url"`

	// Authentication configuration. Valid values: `CLOSE`, `UPDATE`
	// `CLOSE`: disable authentication
	// `UPDATE`: update authentication information
	ActionType *string `json:"ActionType,omitnil,omitempty" name:"ActionType"`
}

func (r *ModifyStreamPackageChannelInputAuthInfoRequest) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *ModifyStreamPackageChannelInputAuthInfoRequest) FromJsonString(s string) error {
	f := make(map[string]interface{})
	if err := json.Unmarshal([]byte(s), &f); err != nil {
		return err
	}
	delete(f, "Id")
	delete(f, "Url")
	delete(f, "ActionType")
	if len(f) > 0 {
		return tcerr.NewTencentCloudSDKError("ClientError.BuildRequestError", "ModifyStreamPackageChannelInputAuthInfoRequest has unknown keys!", "")
	}
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type ModifyStreamPackageChannelInputAuthInfoResponseParams struct {
	// Channel input authentication information
	AuthInfo *InputAuthInfo `json:"AuthInfo,omitnil,omitempty" name:"AuthInfo"`

	// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
	RequestId *string `json:"RequestId,omitnil,omitempty" name:"RequestId"`
}

type ModifyStreamPackageChannelInputAuthInfoResponse struct {
	*tchttp.BaseResponse
	Response *ModifyStreamPackageChannelInputAuthInfoResponseParams `json:"Response"`
}

func (r *ModifyStreamPackageChannelInputAuthInfoResponse) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *ModifyStreamPackageChannelInputAuthInfoResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type ModifyStreamPackageChannelRequestParams struct {
	// Channel ID
	Id *string `json:"Id,omitnil,omitempty" name:"Id"`

	// New channel name
	Name *string `json:"Name,omitnil,omitempty" name:"Name"`

	// New channel protocol. Valid values: HLS, DASH
	Protocol *string `json:"Protocol,omitnil,omitempty" name:"Protocol"`

	// Cache configuration
	CacheInfo *CacheInfo `json:"CacheInfo,omitnil,omitempty" name:"CacheInfo"`
}

type ModifyStreamPackageChannelRequest struct {
	*tchttp.BaseRequest
	
	// Channel ID
	Id *string `json:"Id,omitnil,omitempty" name:"Id"`

	// New channel name
	Name *string `json:"Name,omitnil,omitempty" name:"Name"`

	// New channel protocol. Valid values: HLS, DASH
	Protocol *string `json:"Protocol,omitnil,omitempty" name:"Protocol"`

	// Cache configuration
	CacheInfo *CacheInfo `json:"CacheInfo,omitnil,omitempty" name:"CacheInfo"`
}

func (r *ModifyStreamPackageChannelRequest) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *ModifyStreamPackageChannelRequest) FromJsonString(s string) error {
	f := make(map[string]interface{})
	if err := json.Unmarshal([]byte(s), &f); err != nil {
		return err
	}
	delete(f, "Id")
	delete(f, "Name")
	delete(f, "Protocol")
	delete(f, "CacheInfo")
	if len(f) > 0 {
		return tcerr.NewTencentCloudSDKError("ClientError.BuildRequestError", "ModifyStreamPackageChannelRequest has unknown keys!", "")
	}
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type ModifyStreamPackageChannelResponseParams struct {
	// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
	RequestId *string `json:"RequestId,omitnil,omitempty" name:"RequestId"`
}

type ModifyStreamPackageChannelResponse struct {
	*tchttp.BaseResponse
	Response *ModifyStreamPackageChannelResponseParams `json:"Response"`
}

func (r *ModifyStreamPackageChannelResponse) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *ModifyStreamPackageChannelResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

type PointInfo struct {
	// Channel input list.
	Inputs []*InputInfo `json:"Inputs,omitnil,omitempty" name:"Inputs"`

	// Channel output list.
	// Note: this field may return null, indicating that no valid values can be obtained.
	Endpoints []*EndpointInfo `json:"Endpoints,omitnil,omitempty" name:"Endpoints"`
}

type SSAIConf struct {
	// Advertising Decision Server URL (ADS).
	AdsUrl *string `json:"AdsUrl,omitnil,omitempty" name:"AdsUrl"`

	// Parameter configuration.
	ConfigAliases []*ConfigAliasesInfo `json:"ConfigAliases,omitnil,omitempty" name:"ConfigAliases"`

	// Default advertising url.
	SlateAd *string `json:"SlateAd,omitnil,omitempty" name:"SlateAd"`

	// Maximum unfilled duration, unit: seconds.
	Threshold *uint64 `json:"Threshold,omitnil,omitempty" name:"Threshold"`

	// Whether to enable mpd location, true corresponds to enable, false corresponds to disable.
	DashMPDLocation *bool `json:"DashMPDLocation,omitnil,omitempty" name:"DashMPDLocation"`

	// Whether to enable transparent transmission of advertising tags.
	AdMarkerPassthrough *bool `json:"AdMarkerPassthrough,omitnil,omitempty" name:"AdMarkerPassthrough"`

	// How to process tags in advertisements, optional values: [1,2] 
	// 1: Process all SCTE-35 type tags - all (default) 
	// 2: SCTE-35enhanced, parse some types.
	SCTE35AdType *uint64 `json:"SCTE35AdType,omitnil,omitempty" name:"SCTE35AdType"`

	// The type of tag that is regarded as an advertisement, optional values: [1,8]
	// 1. Splice insert 
	// 2. Provider advertisement 
	// 3. Distributor advertisement 
	// 4. Provider placement opportunity 
	// 5. Distributor placement opportunity 
	// 6. Break 
	// 7. Provider overlay placement opportunity 
	// 8. Distributor overlay placement opportunity.
	AdTriggers []*uint64 `json:"AdTriggers,omitnil,omitempty" name:"AdTriggers"`

	// The type of distribution restriction that is considered an advertisement, optional values: [1,4]
	// 1:None 
	// 2:Restricted (default) 
	// 3:Unrestricted 
	// 4.Both.
	DeliveryRestrictions *uint64 `json:"DeliveryRestrictions,omitnil,omitempty" name:"DeliveryRestrictions"`
}

// Predefined struct for user
type UnbindCdnDomainWithChannelRequestParams struct {
	// Channel ID
	ChannelId *string `json:"ChannelId,omitnil,omitempty" name:"ChannelId"`

	// CDN playback domain name
	CdnDomain *string `json:"CdnDomain,omitnil,omitempty" name:"CdnDomain"`
}

type UnbindCdnDomainWithChannelRequest struct {
	*tchttp.BaseRequest
	
	// Channel ID
	ChannelId *string `json:"ChannelId,omitnil,omitempty" name:"ChannelId"`

	// CDN playback domain name
	CdnDomain *string `json:"CdnDomain,omitnil,omitempty" name:"CdnDomain"`
}

func (r *UnbindCdnDomainWithChannelRequest) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *UnbindCdnDomainWithChannelRequest) FromJsonString(s string) error {
	f := make(map[string]interface{})
	if err := json.Unmarshal([]byte(s), &f); err != nil {
		return err
	}
	delete(f, "ChannelId")
	delete(f, "CdnDomain")
	if len(f) > 0 {
		return tcerr.NewTencentCloudSDKError("ClientError.BuildRequestError", "UnbindCdnDomainWithChannelRequest has unknown keys!", "")
	}
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type UnbindCdnDomainWithChannelResponseParams struct {
	// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
	RequestId *string `json:"RequestId,omitnil,omitempty" name:"RequestId"`
}

type UnbindCdnDomainWithChannelResponse struct {
	*tchttp.BaseResponse
	Response *UnbindCdnDomainWithChannelResponseParams `json:"Response"`
}

func (r *UnbindCdnDomainWithChannelResponse) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *UnbindCdnDomainWithChannelResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}