// Copyright (c) 2017-2025 Tencent. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package v20250106

import (
    tcerr "github.com/tencentcloud/tencentcloud-sdk-go-intl-en/tencentcloud/common/errors"
    tchttp "github.com/tencentcloud/tencentcloud-sdk-go-intl-en/tencentcloud/common/http"
    "github.com/tencentcloud/tencentcloud-sdk-go-intl-en/tencentcloud/common/json"
)

// Predefined struct for user
type DescribeMNGMAUDataDetailRequestParams struct {
	// Type
	DataType *int64 `json:"DataType,omitnil,omitempty" name:"DataType"`

	// Tenant ID
	PlatformId *string `json:"PlatformId,omitnil,omitempty" name:"PlatformId"`

	// Superapp ID
	ApplicationId *string `json:"ApplicationId,omitnil,omitempty" name:"ApplicationId"`

	// Mini program appid, required. When provided, the query is performed based on the mini program.
	MNPId *string `json:"MNPId,omitnil,omitempty" name:"MNPId"`

	// Mini program team ID
	MNPTeamId *int64 `json:"MNPTeamId,omitnil,omitempty" name:"MNPTeamId"`
}

type DescribeMNGMAUDataDetailRequest struct {
	*tchttp.BaseRequest
	
	// Type
	DataType *int64 `json:"DataType,omitnil,omitempty" name:"DataType"`

	// Tenant ID
	PlatformId *string `json:"PlatformId,omitnil,omitempty" name:"PlatformId"`

	// Superapp ID
	ApplicationId *string `json:"ApplicationId,omitnil,omitempty" name:"ApplicationId"`

	// Mini program appid, required. When provided, the query is performed based on the mini program.
	MNPId *string `json:"MNPId,omitnil,omitempty" name:"MNPId"`

	// Mini program team ID
	MNPTeamId *int64 `json:"MNPTeamId,omitnil,omitempty" name:"MNPTeamId"`
}

func (r *DescribeMNGMAUDataDetailRequest) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *DescribeMNGMAUDataDetailRequest) FromJsonString(s string) error {
	f := make(map[string]interface{})
	if err := json.Unmarshal([]byte(s), &f); err != nil {
		return err
	}
	delete(f, "DataType")
	delete(f, "PlatformId")
	delete(f, "ApplicationId")
	delete(f, "MNPId")
	delete(f, "MNPTeamId")
	if len(f) > 0 {
		return tcerr.NewTencentCloudSDKError("ClientError.BuildRequestError", "DescribeMNGMAUDataDetailRequest has unknown keys!", "")
	}
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type DescribeMNGMAUDataDetailResponseParams struct {
	// Data display
	// Note: This field may return null, indicating that no valid values can be obtained.
	Data []*MAUDetail `json:"Data,omitnil,omitempty" name:"Data"`

	// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
	RequestId *string `json:"RequestId,omitnil,omitempty" name:"RequestId"`
}

type DescribeMNGMAUDataDetailResponse struct {
	*tchttp.BaseResponse
	Response *DescribeMNGMAUDataDetailResponseParams `json:"Response"`
}

func (r *DescribeMNGMAUDataDetailResponse) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *DescribeMNGMAUDataDetailResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type DescribeMNGMAULineChartRequestParams struct {
	// Type: 0 Non-production data, 1 Production data 
	DataType *int64 `json:"DataType,omitnil,omitempty" name:"DataType"`

	// Tenant ID
	PlatformId *string `json:"PlatformId,omitnil,omitempty" name:"PlatformId"`

	// Superapp ID
	ApplicationId *string `json:"ApplicationId,omitnil,omitempty" name:"ApplicationId"`

	// Mini program appid, required. When provided, the query is performed based on the mini program.
	MNPId *string `json:"MNPId,omitnil,omitempty" name:"MNPId"`

	// Mini program team ID
	MNPTeamId *int64 `json:"MNPTeamId,omitnil,omitempty" name:"MNPTeamId"`
}

type DescribeMNGMAULineChartRequest struct {
	*tchttp.BaseRequest
	
	// Type: 0 Non-production data, 1 Production data 
	DataType *int64 `json:"DataType,omitnil,omitempty" name:"DataType"`

	// Tenant ID
	PlatformId *string `json:"PlatformId,omitnil,omitempty" name:"PlatformId"`

	// Superapp ID
	ApplicationId *string `json:"ApplicationId,omitnil,omitempty" name:"ApplicationId"`

	// Mini program appid, required. When provided, the query is performed based on the mini program.
	MNPId *string `json:"MNPId,omitnil,omitempty" name:"MNPId"`

	// Mini program team ID
	MNPTeamId *int64 `json:"MNPTeamId,omitnil,omitempty" name:"MNPTeamId"`
}

func (r *DescribeMNGMAULineChartRequest) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *DescribeMNGMAULineChartRequest) FromJsonString(s string) error {
	f := make(map[string]interface{})
	if err := json.Unmarshal([]byte(s), &f); err != nil {
		return err
	}
	delete(f, "DataType")
	delete(f, "PlatformId")
	delete(f, "ApplicationId")
	delete(f, "MNPId")
	delete(f, "MNPTeamId")
	if len(f) > 0 {
		return tcerr.NewTencentCloudSDKError("ClientError.BuildRequestError", "DescribeMNGMAULineChartRequest has unknown keys!", "")
	}
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type DescribeMNGMAULineChartResponseParams struct {
	// Data display at the top of the page
	// Note: This field may return null, indicating that no valid values can be obtained.
	Data []*MNGMAULineChartData `json:"Data,omitnil,omitempty" name:"Data"`

	// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
	RequestId *string `json:"RequestId,omitnil,omitempty" name:"RequestId"`
}

type DescribeMNGMAULineChartResponse struct {
	*tchttp.BaseResponse
	Response *DescribeMNGMAULineChartResponseParams `json:"Response"`
}

func (r *DescribeMNGMAULineChartResponse) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *DescribeMNGMAULineChartResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type DescribeMNGMAUMonthlyComparisonMetricCardRequestParams struct {
	// Start time in YYYYMMDD format
	SourceMonth *int64 `json:"SourceMonth,omitnil,omitempty" name:"SourceMonth"`

	// Type: 0 Non-production data, 1 Production data 
	DataType *int64 `json:"DataType,omitnil,omitempty" name:"DataType"`

	// Tenant ID
	PlatformId *string `json:"PlatformId,omitnil,omitempty" name:"PlatformId"`

	// End time in YYYYMMDD format
	TargetMonth *int64 `json:"TargetMonth,omitnil,omitempty" name:"TargetMonth"`

	// Superapp ID starting with App
	ApplicationId *string `json:"ApplicationId,omitnil,omitempty" name:"ApplicationId"`

	// Mini program appid, required. When provided, the query is performed based on the mini program.
	MNPId *string `json:"MNPId,omitnil,omitempty" name:"MNPId"`

	// Mini program team ID, required. When provided, the query is performed based on the mini program team.
	MNPTeamId *int64 `json:"MNPTeamId,omitnil,omitempty" name:"MNPTeamId"`
}

type DescribeMNGMAUMonthlyComparisonMetricCardRequest struct {
	*tchttp.BaseRequest
	
	// Start time in YYYYMMDD format
	SourceMonth *int64 `json:"SourceMonth,omitnil,omitempty" name:"SourceMonth"`

	// Type: 0 Non-production data, 1 Production data 
	DataType *int64 `json:"DataType,omitnil,omitempty" name:"DataType"`

	// Tenant ID
	PlatformId *string `json:"PlatformId,omitnil,omitempty" name:"PlatformId"`

	// End time in YYYYMMDD format
	TargetMonth *int64 `json:"TargetMonth,omitnil,omitempty" name:"TargetMonth"`

	// Superapp ID starting with App
	ApplicationId *string `json:"ApplicationId,omitnil,omitempty" name:"ApplicationId"`

	// Mini program appid, required. When provided, the query is performed based on the mini program.
	MNPId *string `json:"MNPId,omitnil,omitempty" name:"MNPId"`

	// Mini program team ID, required. When provided, the query is performed based on the mini program team.
	MNPTeamId *int64 `json:"MNPTeamId,omitnil,omitempty" name:"MNPTeamId"`
}

func (r *DescribeMNGMAUMonthlyComparisonMetricCardRequest) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *DescribeMNGMAUMonthlyComparisonMetricCardRequest) FromJsonString(s string) error {
	f := make(map[string]interface{})
	if err := json.Unmarshal([]byte(s), &f); err != nil {
		return err
	}
	delete(f, "SourceMonth")
	delete(f, "DataType")
	delete(f, "PlatformId")
	delete(f, "TargetMonth")
	delete(f, "ApplicationId")
	delete(f, "MNPId")
	delete(f, "MNPTeamId")
	if len(f) > 0 {
		return tcerr.NewTencentCloudSDKError("ClientError.BuildRequestError", "DescribeMNGMAUMonthlyComparisonMetricCardRequest has unknown keys!", "")
	}
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type DescribeMNGMAUMonthlyComparisonMetricCardResponseParams struct {
	// Data display at the top of the page
	Data *MAUIndicatorCard `json:"Data,omitnil,omitempty" name:"Data"`

	// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
	RequestId *string `json:"RequestId,omitnil,omitempty" name:"RequestId"`
}

type DescribeMNGMAUMonthlyComparisonMetricCardResponse struct {
	*tchttp.BaseResponse
	Response *DescribeMNGMAUMonthlyComparisonMetricCardResponseParams `json:"Response"`
}

func (r *DescribeMNGMAUMonthlyComparisonMetricCardResponse) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *DescribeMNGMAUMonthlyComparisonMetricCardResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type DescribeMNPMAUDataDetailRequestParams struct {
	// Type: 0 Non-production data, 1 Production data
	DataType *int64 `json:"DataType,omitnil,omitempty" name:"DataType"`

	// Tenant ID
	PlatformId *string `json:"PlatformId,omitnil,omitempty" name:"PlatformId"`

	// Superapp ID
	ApplicationId *string `json:"ApplicationId,omitnil,omitempty" name:"ApplicationId"`

	// Mini program appid, required. When provided, the query is performed based on the mini program.
	MNPId *string `json:"MNPId,omitnil,omitempty" name:"MNPId"`

	// Program team ID, -1 means not provided
	MNPTeamId *int64 `json:"MNPTeamId,omitnil,omitempty" name:"MNPTeamId"`
}

type DescribeMNPMAUDataDetailRequest struct {
	*tchttp.BaseRequest
	
	// Type: 0 Non-production data, 1 Production data
	DataType *int64 `json:"DataType,omitnil,omitempty" name:"DataType"`

	// Tenant ID
	PlatformId *string `json:"PlatformId,omitnil,omitempty" name:"PlatformId"`

	// Superapp ID
	ApplicationId *string `json:"ApplicationId,omitnil,omitempty" name:"ApplicationId"`

	// Mini program appid, required. When provided, the query is performed based on the mini program.
	MNPId *string `json:"MNPId,omitnil,omitempty" name:"MNPId"`

	// Program team ID, -1 means not provided
	MNPTeamId *int64 `json:"MNPTeamId,omitnil,omitempty" name:"MNPTeamId"`
}

func (r *DescribeMNPMAUDataDetailRequest) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *DescribeMNPMAUDataDetailRequest) FromJsonString(s string) error {
	f := make(map[string]interface{})
	if err := json.Unmarshal([]byte(s), &f); err != nil {
		return err
	}
	delete(f, "DataType")
	delete(f, "PlatformId")
	delete(f, "ApplicationId")
	delete(f, "MNPId")
	delete(f, "MNPTeamId")
	if len(f) > 0 {
		return tcerr.NewTencentCloudSDKError("ClientError.BuildRequestError", "DescribeMNPMAUDataDetailRequest has unknown keys!", "")
	}
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type DescribeMNPMAUDataDetailResponseParams struct {
	// Data display
	// Note: This field may return null, indicating that no valid values can be obtained.
	Data []*MAUDetail `json:"Data,omitnil,omitempty" name:"Data"`

	// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
	RequestId *string `json:"RequestId,omitnil,omitempty" name:"RequestId"`
}

type DescribeMNPMAUDataDetailResponse struct {
	*tchttp.BaseResponse
	Response *DescribeMNPMAUDataDetailResponseParams `json:"Response"`
}

func (r *DescribeMNPMAUDataDetailResponse) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *DescribeMNPMAUDataDetailResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type DescribeMNPMAULineChartRequestParams struct {
	// Type: 0 Non-production data, 1 Production data
	DataType *int64 `json:"DataType,omitnil,omitempty" name:"DataType"`

	// Tenant ID
	PlatformId *string `json:"PlatformId,omitnil,omitempty" name:"PlatformId"`

	// Superapp ID
	ApplicationId *string `json:"ApplicationId,omitnil,omitempty" name:"ApplicationId"`

	// Mini program appid, required. When provided, the query is performed based on the mini program.
	MNPId *string `json:"MNPId,omitnil,omitempty" name:"MNPId"`

	// Mini program team ID
	MNPTeamId *int64 `json:"MNPTeamId,omitnil,omitempty" name:"MNPTeamId"`
}

type DescribeMNPMAULineChartRequest struct {
	*tchttp.BaseRequest
	
	// Type: 0 Non-production data, 1 Production data
	DataType *int64 `json:"DataType,omitnil,omitempty" name:"DataType"`

	// Tenant ID
	PlatformId *string `json:"PlatformId,omitnil,omitempty" name:"PlatformId"`

	// Superapp ID
	ApplicationId *string `json:"ApplicationId,omitnil,omitempty" name:"ApplicationId"`

	// Mini program appid, required. When provided, the query is performed based on the mini program.
	MNPId *string `json:"MNPId,omitnil,omitempty" name:"MNPId"`

	// Mini program team ID
	MNPTeamId *int64 `json:"MNPTeamId,omitnil,omitempty" name:"MNPTeamId"`
}

func (r *DescribeMNPMAULineChartRequest) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *DescribeMNPMAULineChartRequest) FromJsonString(s string) error {
	f := make(map[string]interface{})
	if err := json.Unmarshal([]byte(s), &f); err != nil {
		return err
	}
	delete(f, "DataType")
	delete(f, "PlatformId")
	delete(f, "ApplicationId")
	delete(f, "MNPId")
	delete(f, "MNPTeamId")
	if len(f) > 0 {
		return tcerr.NewTencentCloudSDKError("ClientError.BuildRequestError", "DescribeMNPMAULineChartRequest has unknown keys!", "")
	}
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type DescribeMNPMAULineChartResponseParams struct {
	// Data display
	// Note: This field may return null, indicating that no valid values can be obtained.
	Data []*MAUChartData `json:"Data,omitnil,omitempty" name:"Data"`

	// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
	RequestId *string `json:"RequestId,omitnil,omitempty" name:"RequestId"`
}

type DescribeMNPMAULineChartResponse struct {
	*tchttp.BaseResponse
	Response *DescribeMNPMAULineChartResponseParams `json:"Response"`
}

func (r *DescribeMNPMAULineChartResponse) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *DescribeMNPMAULineChartResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type DescribeMNPMAUMetricCardRequestParams struct {
	// Start time in YYYYMMDD format
	SourceMonth *int64 `json:"SourceMonth,omitnil,omitempty" name:"SourceMonth"`

	// Type: 0 Non-production data, 1 Production data 
	DataType *int64 `json:"DataType,omitnil,omitempty" name:"DataType"`

	// Tenant ID
	PlatformId *string `json:"PlatformId,omitnil,omitempty" name:"PlatformId"`

	// End time in YYYYMMDD format
	TargetMonth *int64 `json:"TargetMonth,omitnil,omitempty" name:"TargetMonth"`

	// Superapp ID starting with App
	ApplicationId *string `json:"ApplicationId,omitnil,omitempty" name:"ApplicationId"`

	// Mini program appid, required. When provided, the query is performed based on the mini program.
	MNPId *string `json:"MNPId,omitnil,omitempty" name:"MNPId"`

	// Mini program team ID, required. When provided, the query is performed based on the mini program team.
	MNPTeamId *int64 `json:"MNPTeamId,omitnil,omitempty" name:"MNPTeamId"`
}

type DescribeMNPMAUMetricCardRequest struct {
	*tchttp.BaseRequest
	
	// Start time in YYYYMMDD format
	SourceMonth *int64 `json:"SourceMonth,omitnil,omitempty" name:"SourceMonth"`

	// Type: 0 Non-production data, 1 Production data 
	DataType *int64 `json:"DataType,omitnil,omitempty" name:"DataType"`

	// Tenant ID
	PlatformId *string `json:"PlatformId,omitnil,omitempty" name:"PlatformId"`

	// End time in YYYYMMDD format
	TargetMonth *int64 `json:"TargetMonth,omitnil,omitempty" name:"TargetMonth"`

	// Superapp ID starting with App
	ApplicationId *string `json:"ApplicationId,omitnil,omitempty" name:"ApplicationId"`

	// Mini program appid, required. When provided, the query is performed based on the mini program.
	MNPId *string `json:"MNPId,omitnil,omitempty" name:"MNPId"`

	// Mini program team ID, required. When provided, the query is performed based on the mini program team.
	MNPTeamId *int64 `json:"MNPTeamId,omitnil,omitempty" name:"MNPTeamId"`
}

func (r *DescribeMNPMAUMetricCardRequest) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *DescribeMNPMAUMetricCardRequest) FromJsonString(s string) error {
	f := make(map[string]interface{})
	if err := json.Unmarshal([]byte(s), &f); err != nil {
		return err
	}
	delete(f, "SourceMonth")
	delete(f, "DataType")
	delete(f, "PlatformId")
	delete(f, "TargetMonth")
	delete(f, "ApplicationId")
	delete(f, "MNPId")
	delete(f, "MNPTeamId")
	if len(f) > 0 {
		return tcerr.NewTencentCloudSDKError("ClientError.BuildRequestError", "DescribeMNPMAUMetricCardRequest has unknown keys!", "")
	}
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type DescribeMNPMAUMetricCardResponseParams struct {
	// Data display at the top of the page
	Data *MAUIndicatorCard `json:"Data,omitnil,omitempty" name:"Data"`

	// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
	RequestId *string `json:"RequestId,omitnil,omitempty" name:"RequestId"`
}

type DescribeMNPMAUMetricCardResponse struct {
	*tchttp.BaseResponse
	Response *DescribeMNPMAUMetricCardResponseParams `json:"Response"`
}

func (r *DescribeMNPMAUMetricCardResponse) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *DescribeMNPMAUMetricCardResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

type MAUChartData struct {
	// Year and month: 2024-12
	DataTime *int64 `json:"DataTime,omitnil,omitempty" name:"DataTime"`

	// Value
	MAUCount *int64 `json:"MAUCount,omitnil,omitempty" name:"MAUCount"`

	// Data update time, only available when MAUCount is greater than 0.
	UpdateTime *int64 `json:"UpdateTime,omitnil,omitempty" name:"UpdateTime"`
}

type MAUDetail struct {
	// Mini program name
	MNPName *string `json:"MNPName,omitnil,omitempty" name:"MNPName"`

	// MAU details
	DataList []*MAULineChartData `json:"DataList,omitnil,omitempty" name:"DataList"`
}

type MAUIndicatorCard struct {
	// Growth rate (targetData - sourceData) / sourceData, returns 0 when SourceMAUNum is 0
	ComparisonRatio *string `json:"ComparisonRatio,omitnil,omitempty" name:"ComparisonRatio"`

	// 1 Increase
	// 2 Decrease
	// Returns 0 when SourceMAUNum is 0
	ComparisonResult *int64 `json:"ComparisonResult,omitnil,omitempty" name:"ComparisonResult"`

	// Last month's MAU data
	SourceMAUNum *int64 `json:"SourceMAUNum,omitnil,omitempty" name:"SourceMAUNum"`

	// This month's MAU data
	TargetMAUNum *int64 `json:"TargetMAUNum,omitnil,omitempty" name:"TargetMAUNum"`

	// Data timestamp
	FlushTime *int64 `json:"FlushTime,omitnil,omitempty" name:"FlushTime"`
}

type MAULineChartData struct {
	// Year-month date data
	// Note: This field may return null, indicating that no valid values can be obtained.
	DataTime *int64 `json:"DataTime,omitnil,omitempty" name:"DataTime"`

	// MAU data
	// Note: This field may return null, indicating that no valid values can be obtained.
	MAUCount *string `json:"MAUCount,omitnil,omitempty" name:"MAUCount"`
}

type MNGMAULineChartData struct {
	// Year-month-date data
	// Note: This field may return null, indicating that no valid values can be obtained.
	DataTime *int64 `json:"DataTime,omitnil,omitempty" name:"DataTime"`

	// MAU data
	// Note: This field may return null, indicating that no valid values can be obtained.
	MAUCount *int64 `json:"MAUCount,omitnil,omitempty" name:"MAUCount"`

	// Update time
	UpdateTime *int64 `json:"UpdateTime,omitnil,omitempty" name:"UpdateTime"`
}