// Copyright (c) 2017-2025 Tencent. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package v20250101

import (
    tcerr "github.com/tencentcloud/tencentcloud-sdk-go-intl-en/tencentcloud/common/errors"
    tchttp "github.com/tencentcloud/tencentcloud-sdk-go-intl-en/tencentcloud/common/http"
    "github.com/tencentcloud/tencentcloud-sdk-go-intl-en/tencentcloud/common/json"
)

type Chunk struct {
	// chunk index. Slice sequence id.
	Index *uint64 `json:"Index,omitnil,omitempty" name:"Index"`

	// chunk content.
	Content *string `json:"Content,omitnil,omitempty" name:"Content"`
}

type ChunkConfig struct {
	// After splitting by the separator, the fragment length is validated. If it exceeds the maximum fragment length, it is split using the next-level separator. If there is no next-level separator, the original length is retained. Default value: 1000.
	MaxChunkSize *uint64 `json:"MaxChunkSize,omitnil,omitempty" name:"MaxChunkSize"`

	// Separator list, separators positioned towards the front take precedence; when the file type is TXT, default value: ["\n\n", "\n", ".", ".", "?", ",", ""].
	Delimiters []*string `json:"Delimiters,omitnil,omitempty" name:"Delimiters"`

	// The number of overlapping characters between adjacent fragments must be less than the fragment length. Fragments that form completely redundant slices are automatically filtered. Default value: 0.2*MaxChunkSize
	ChunkOverlap *uint64 `json:"ChunkOverlap,omitnil,omitempty" name:"ChunkOverlap"`
}

type ChunkConfigAsync struct {
	// Maximum fragment length
	MaxChunkSize *int64 `json:"MaxChunkSize,omitnil,omitempty" name:"MaxChunkSize"`
}

type ChunkDocument struct {
	// File type, supports MD and TXT formats.
	FileType *string `json:"FileType,omitnil,omitempty" name:"FileType"`

	// Text original, use string format input.
	FileContent *string `json:"FileContent,omitnil,omitempty" name:"FileContent"`
}

// Predefined struct for user
type ChunkDocumentAsyncRequestParams struct {
	// File information.
	Document *Document `json:"Document,omitnil,omitempty" name:"Document"`

	// Model name, selectable model list: doc-tree-chunk.
	ModelName *string `json:"ModelName,omitnil,omitempty" name:"ModelName"`

	// File slice configuration.
	Config *ChunkConfigAsync `json:"Config,omitnil,omitempty" name:"Config"`
}

type ChunkDocumentAsyncRequest struct {
	*tchttp.BaseRequest
	
	// File information.
	Document *Document `json:"Document,omitnil,omitempty" name:"Document"`

	// Model name, selectable model list: doc-tree-chunk.
	ModelName *string `json:"ModelName,omitnil,omitempty" name:"ModelName"`

	// File slice configuration.
	Config *ChunkConfigAsync `json:"Config,omitnil,omitempty" name:"Config"`
}

func (r *ChunkDocumentAsyncRequest) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *ChunkDocumentAsyncRequest) FromJsonString(s string) error {
	f := make(map[string]interface{})
	if err := json.Unmarshal([]byte(s), &f); err != nil {
		return err
	}
	delete(f, "Document")
	delete(f, "ModelName")
	delete(f, "Config")
	if len(f) > 0 {
		return tcerr.NewTencentCloudSDKError("ClientError.BuildRequestError", "ChunkDocumentAsyncRequest has unknown keys!", "")
	}
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type ChunkDocumentAsyncResponseParams struct {
	// Task ID
	TaskId *string `json:"TaskId,omitnil,omitempty" name:"TaskId"`

	// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
	RequestId *string `json:"RequestId,omitnil,omitempty" name:"RequestId"`
}

type ChunkDocumentAsyncResponse struct {
	*tchttp.BaseResponse
	Response *ChunkDocumentAsyncResponseParams `json:"Response"`
}

func (r *ChunkDocumentAsyncResponse) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *ChunkDocumentAsyncResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type ChunkDocumentRequestParams struct {
	// Slice file info.
	Document *ChunkDocument `json:"Document,omitnil,omitempty" name:"Document"`

	// Model name, selectable model list: doc-chunk.
	ModelName *string `json:"ModelName,omitnil,omitempty" name:"ModelName"`

	// File slice configuration.
	Config *ChunkConfig `json:"Config,omitnil,omitempty" name:"Config"`
}

type ChunkDocumentRequest struct {
	*tchttp.BaseRequest
	
	// Slice file info.
	Document *ChunkDocument `json:"Document,omitnil,omitempty" name:"Document"`

	// Model name, selectable model list: doc-chunk.
	ModelName *string `json:"ModelName,omitnil,omitempty" name:"ModelName"`

	// File slice configuration.
	Config *ChunkConfig `json:"Config,omitnil,omitempty" name:"Config"`
}

func (r *ChunkDocumentRequest) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *ChunkDocumentRequest) FromJsonString(s string) error {
	f := make(map[string]interface{})
	if err := json.Unmarshal([]byte(s), &f); err != nil {
		return err
	}
	delete(f, "Document")
	delete(f, "ModelName")
	delete(f, "Config")
	if len(f) > 0 {
		return tcerr.NewTencentCloudSDKError("ClientError.BuildRequestError", "ChunkDocumentRequest has unknown keys!", "")
	}
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type ChunkDocumentResponseParams struct {
	// None.
	Chunks []*Chunk `json:"Chunks,omitnil,omitempty" name:"Chunks"`

	// token consumption
	Usage *Usage `json:"Usage,omitnil,omitempty" name:"Usage"`

	// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
	RequestId *string `json:"RequestId,omitnil,omitempty" name:"RequestId"`
}

type ChunkDocumentResponse struct {
	*tchttp.BaseResponse
	Response *ChunkDocumentResponseParams `json:"Response"`
}

func (r *ChunkDocumentResponse) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *ChunkDocumentResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

type Document struct {
	// Supported file types: PDF, DOC, DOCX, PPT, PPTX, MD, TXT, XLS.
	// XLSX,CSV,PNG,JPG,JPEG,BMP,GIF,WEBP,HEIC,EPS,ICNS,
	// IM,PCX,PPM,TIFF,XBM,HEIF,JP2
	// 
	// Supported file size for document parsing:
	// -PDF, DOC, DOCX, PPT, PPTX support 100M.
	// -MD, TXT, XLS, XLSX, CSV support 10M.
	// -Other supports 20M
	// 
	// Supported file size for text slicing:
	// -Maximum PDF size: 300 MB
	// -D0CX, D0C, PPT, PPTX maximum 200M
	// -Maximum 10M for TXT, MD
	// -Another maximum of 20M
	FileType *string `json:"FileType,omitnil,omitempty" name:"FileType"`

	// File storage on Tencent Cloud's URL ensures higher download speed and stability by using Tencent Cloud COS file address.
	FileUrl *string `json:"FileUrl,omitnil,omitempty" name:"FileUrl"`

	// base64 value of the file, carrying the MineType prefix information. The encoded file is no more than 10M.
	// Supported file size: The downloaded file is no more than 8M after Base64 encoding. File download time is not more than 3 seconds.
	// Supported image pixel: Unilateral between 20-10000px.
	FileContent *string `json:"FileContent,omitnil,omitempty" name:"FileContent"`

	// File name, used when uploading with base64.
	FileName *string `json:"FileName,omitnil,omitempty" name:"FileName"`

	// Starting page number of the document
	FileStartPageNumber *int64 `json:"FileStartPageNumber,omitnil,omitempty" name:"FileStartPageNumber"`

	// End page number of the document
	FileEndPageNumber *int64 `json:"FileEndPageNumber,omitnil,omitempty" name:"FileEndPageNumber"`
}

type DocumentChunkUsage struct {
	// Parse page count
	PageNumber *int64 `json:"PageNumber,omitnil,omitempty" name:"PageNumber"`

	// token consumption
	TotalTokens *int64 `json:"TotalTokens,omitnil,omitempty" name:"TotalTokens"`
}

type DocumentParseConfig struct {
	// 0: Images are returned in link format
	// 1:Return the text content extracted from the image
	ImageResponseType *uint64 `json:"ImageResponseType,omitnil,omitempty" name:"ImageResponseType"`
}

type EmbeddingData struct {
	// embedding content
	// Note: This field may return null, indicating that no valid values can be obtained.
	Embedding []*float64 `json:"Embedding,omitnil,omitempty" name:"Embedding"`

	// Index serial number
	// Note: This field may return null, indicating that no valid values can be obtained.
	Index *int64 `json:"Index,omitnil,omitempty" name:"Index"`
}

// Predefined struct for user
type GetDocumentChunkResultRequestParams struct {
	// Task ID
	TaskId *string `json:"TaskId,omitnil,omitempty" name:"TaskId"`
}

type GetDocumentChunkResultRequest struct {
	*tchttp.BaseRequest
	
	// Task ID
	TaskId *string `json:"TaskId,omitnil,omitempty" name:"TaskId"`
}

func (r *GetDocumentChunkResultRequest) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *GetDocumentChunkResultRequest) FromJsonString(s string) error {
	f := make(map[string]interface{})
	if err := json.Unmarshal([]byte(s), &f); err != nil {
		return err
	}
	delete(f, "TaskId")
	if len(f) > 0 {
		return tcerr.NewTencentCloudSDKError("ClientError.BuildRequestError", "GetDocumentChunkResultRequest has unknown keys!", "")
	}
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type GetDocumentChunkResultResponseParams struct {
	// Task status, -1: failure, 0: running, 1: success.
	Status *int64 `json:"Status,omitnil,omitempty" name:"Status"`

	// Document slice result file.
	DocumentChunkResultUrl *string `json:"DocumentChunkResultUrl,omitnil,omitempty" name:"DocumentChunkResultUrl"`

	// Token amount.
	Usage *DocumentChunkUsage `json:"Usage,omitnil,omitempty" name:"Usage"`

	// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
	RequestId *string `json:"RequestId,omitnil,omitempty" name:"RequestId"`
}

type GetDocumentChunkResultResponse struct {
	*tchttp.BaseResponse
	Response *GetDocumentChunkResultResponseParams `json:"Response"`
}

func (r *GetDocumentChunkResultResponse) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *GetDocumentChunkResultResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type GetDocumentParseResultRequestParams struct {
	// Task ID.
	TaskId *string `json:"TaskId,omitnil,omitempty" name:"TaskId"`
}

type GetDocumentParseResultRequest struct {
	*tchttp.BaseRequest
	
	// Task ID.
	TaskId *string `json:"TaskId,omitnil,omitempty" name:"TaskId"`
}

func (r *GetDocumentParseResultRequest) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *GetDocumentParseResultRequest) FromJsonString(s string) error {
	f := make(map[string]interface{})
	if err := json.Unmarshal([]byte(s), &f); err != nil {
		return err
	}
	delete(f, "TaskId")
	if len(f) > 0 {
		return tcerr.NewTencentCloudSDKError("ClientError.BuildRequestError", "GetDocumentParseResultRequest has unknown keys!", "")
	}
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type GetDocumentParseResultResponseParams struct {
	// Task status, -1: failure, 0: running, 1: success.
	Status *int64 `json:"Status,omitnil,omitempty" name:"Status"`

	// Result file.
	DocumentParseResultUrl *string `json:"DocumentParseResultUrl,omitnil,omitempty" name:"DocumentParseResultUrl"`

	// Failed page number.
	// Note: This field may return null, indicating that no valid values can be obtained.
	FailedPages []*int64 `json:"FailedPages,omitnil,omitempty" name:"FailedPages"`

	// Page number consumption
	Usage *PageUsage `json:"Usage,omitnil,omitempty" name:"Usage"`

	// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
	RequestId *string `json:"RequestId,omitnil,omitempty" name:"RequestId"`
}

type GetDocumentParseResultResponse struct {
	*tchttp.BaseResponse
	Response *GetDocumentParseResultResponseParams `json:"Response"`
}

func (r *GetDocumentParseResultResponse) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *GetDocumentParseResultResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type GetMultiModalEmbeddingRequestParams struct {

}

type GetMultiModalEmbeddingRequest struct {
	*tchttp.BaseRequest
	
}

func (r *GetMultiModalEmbeddingRequest) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *GetMultiModalEmbeddingRequest) FromJsonString(s string) error {
	f := make(map[string]interface{})
	if err := json.Unmarshal([]byte(s), &f); err != nil {
		return err
	}
	
	if len(f) > 0 {
		return tcerr.NewTencentCloudSDKError("ClientError.BuildRequestError", "GetMultiModalEmbeddingRequest has unknown keys!", "")
	}
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type GetMultiModalEmbeddingResponseParams struct {
	// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
	RequestId *string `json:"RequestId,omitnil,omitempty" name:"RequestId"`
}

type GetMultiModalEmbeddingResponse struct {
	*tchttp.BaseResponse
	Response *GetMultiModalEmbeddingResponseParams `json:"Response"`
}

func (r *GetMultiModalEmbeddingResponse) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *GetMultiModalEmbeddingResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type GetTextEmbeddingRequestParams struct {
	// Model name, selectable model list: bge-base-zh-v1.5, bge-large-zh-v1.5, Conan-embedding-v1, bge-m3, KaLM-embedding-multilingual-mini-v1, Qwen3-Embedding-0.6B.
	ModelName *string `json:"ModelName,omitnil,omitempty" name:"ModelName"`

	// Text set to be vectorized.
	Texts []*string `json:"Texts,omitnil,omitempty" name:"Texts"`
}

type GetTextEmbeddingRequest struct {
	*tchttp.BaseRequest
	
	// Model name, selectable model list: bge-base-zh-v1.5, bge-large-zh-v1.5, Conan-embedding-v1, bge-m3, KaLM-embedding-multilingual-mini-v1, Qwen3-Embedding-0.6B.
	ModelName *string `json:"ModelName,omitnil,omitempty" name:"ModelName"`

	// Text set to be vectorized.
	Texts []*string `json:"Texts,omitnil,omitempty" name:"Texts"`
}

func (r *GetTextEmbeddingRequest) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *GetTextEmbeddingRequest) FromJsonString(s string) error {
	f := make(map[string]interface{})
	if err := json.Unmarshal([]byte(s), &f); err != nil {
		return err
	}
	delete(f, "ModelName")
	delete(f, "Texts")
	if len(f) > 0 {
		return tcerr.NewTencentCloudSDKError("ClientError.BuildRequestError", "GetTextEmbeddingRequest has unknown keys!", "")
	}
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type GetTextEmbeddingResponseParams struct {
	// Result set.
	Data []*EmbeddingData `json:"Data,omitnil,omitempty" name:"Data"`

	// token consumption for vectorization.
	Usage *Usage `json:"Usage,omitnil,omitempty" name:"Usage"`

	// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
	RequestId *string `json:"RequestId,omitnil,omitempty" name:"RequestId"`
}

type GetTextEmbeddingResponse struct {
	*tchttp.BaseResponse
	Response *GetTextEmbeddingResponseParams `json:"Response"`
}

func (r *GetTextEmbeddingResponse) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *GetTextEmbeddingResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

type PageUsage struct {
	// Total number of pages consumed
	TotalPages *int64 `json:"TotalPages,omitnil,omitempty" name:"TotalPages"`
}

type ParseDocument struct {
	// Supported file types: PDF, DOC, DOCX, PPT, PPTX, MD, TXT, XLS.
	// XLSX,CSV,PNG,JPG,JPEG,BMP,GIF,WEBP,HEIC,EPS,ICNS,
	// IM,PCX,PPM,TIFF,XBM,HEIF,JP2
	// 
	// Supported file size for document parsing:
	// -PDF, DOC, DOCX, PPT, PPTX support 100M.
	// -MD, TXT, XLS, XLSX, CSV support 10M.
	// -Another supports 20M
	// 
	// Supported file size for text slicing:
	// -Maximum PDF size: 300 MB
	// -D0CX, D0C, PPT, PPTX maximum 200M
	// -Maximum 10M for TXT, MD
	// -Other maximum 20M
	FileType *string `json:"FileType,omitnil,omitempty" name:"FileType"`

	// File storage on Tencent Cloud's URL ensures higher download speed and stability by using Tencent Cloud COS file address.
	FileUrl *string `json:"FileUrl,omitnil,omitempty" name:"FileUrl"`

	// base64 value of the file, carrying the MineType prefix information. The encoded file is no more than 10M.
	// Supported file size: The downloaded file is no more than 8M after Base64 encoding. File download time is no more than 3 seconds.
	// Supported image pixel: Unilateral between 20-10000px.
	// Either FileUrl or FileContent of the file must be provided. If both are provided, only FileUrl is used.
	FileContent *string `json:"FileContent,omitnil,omitempty" name:"FileContent"`

	// Document parsing configuration
	DocumentParseConfig *DocumentParseConfig `json:"DocumentParseConfig,omitnil,omitempty" name:"DocumentParseConfig"`

	// Starting page number of the document
	FileStartPageNumber *int64 `json:"FileStartPageNumber,omitnil,omitempty" name:"FileStartPageNumber"`

	// End page number of the document
	FileEndPageNumber *int64 `json:"FileEndPageNumber,omitnil,omitempty" name:"FileEndPageNumber"`
}

// Predefined struct for user
type ParseDocumentAsyncRequestParams struct {
	// File information.
	Document *Document `json:"Document,omitnil,omitempty" name:"Document"`

	// Model name, selectable model list: doc-llm.
	ModelName *string `json:"ModelName,omitnil,omitempty" name:"ModelName"`
}

type ParseDocumentAsyncRequest struct {
	*tchttp.BaseRequest
	
	// File information.
	Document *Document `json:"Document,omitnil,omitempty" name:"Document"`

	// Model name, selectable model list: doc-llm.
	ModelName *string `json:"ModelName,omitnil,omitempty" name:"ModelName"`
}

func (r *ParseDocumentAsyncRequest) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *ParseDocumentAsyncRequest) FromJsonString(s string) error {
	f := make(map[string]interface{})
	if err := json.Unmarshal([]byte(s), &f); err != nil {
		return err
	}
	delete(f, "Document")
	delete(f, "ModelName")
	if len(f) > 0 {
		return tcerr.NewTencentCloudSDKError("ClientError.BuildRequestError", "ParseDocumentAsyncRequest has unknown keys!", "")
	}
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type ParseDocumentAsyncResponseParams struct {
	// Task ID
	TaskId *string `json:"TaskId,omitnil,omitempty" name:"TaskId"`

	// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
	RequestId *string `json:"RequestId,omitnil,omitempty" name:"RequestId"`
}

type ParseDocumentAsyncResponse struct {
	*tchttp.BaseResponse
	Response *ParseDocumentAsyncResponseParams `json:"Response"`
}

func (r *ParseDocumentAsyncResponse) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *ParseDocumentAsyncResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type ParseDocumentRequestParams struct {
	// File Information
	Document *ParseDocument `json:"Document,omitnil,omitempty" name:"Document"`

	// Model name, doc-llm.
	ModelName *string `json:"ModelName,omitnil,omitempty" name:"ModelName"`
}

type ParseDocumentRequest struct {
	*tchttp.BaseRequest
	
	// File Information
	Document *ParseDocument `json:"Document,omitnil,omitempty" name:"Document"`

	// Model name, doc-llm.
	ModelName *string `json:"ModelName,omitnil,omitempty" name:"ModelName"`
}

func (r *ParseDocumentRequest) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *ParseDocumentRequest) FromJsonString(s string) error {
	f := make(map[string]interface{})
	if err := json.Unmarshal([]byte(s), &f); err != nil {
		return err
	}
	delete(f, "Document")
	delete(f, "ModelName")
	if len(f) > 0 {
		return tcerr.NewTencentCloudSDKError("ClientError.BuildRequestError", "ParseDocumentRequest has unknown keys!", "")
	}
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type ParseDocumentResponseParams struct {
	// Progress: 0-100.
	Progress *string `json:"Progress,omitnil,omitempty" name:"Progress"`

	// File parsing result.
	DocumentParseResultUrl *string `json:"DocumentParseResultUrl,omitnil,omitempty" name:"DocumentParseResultUrl"`

	// Page number of the failure.
	FailedPages []*int64 `json:"FailedPages,omitnil,omitempty" name:"FailedPages"`

	// Page number consumption
	Usage *PageUsage `json:"Usage,omitnil,omitempty" name:"Usage"`

	// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem. As a streaming response API, when the request is successfully completed, the RequestId will be placed in the Header "X-TC-RequestId" of the HTTP response.
	RequestId *string `json:"RequestId,omitnil,omitempty" name:"RequestId"`
}

type ParseDocumentResponse struct {
	tchttp.BaseSSEResponse `json:"-"`
	Response *ParseDocumentResponseParams `json:"Response"`
}

func (r *ParseDocumentResponse) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *ParseDocumentResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

type RerankResult struct {
	// Location index value of the corresponding doc in the array of candidate docs
	// Note: This field may return null, indicating that no valid values can be obtained.
	Index *int64 `json:"Index,omitnil,omitempty" name:"Index"`

	// Similarity score
	// Note: This field may return null, indicating that no valid values can be obtained.
	RelevanceScore *float64 `json:"RelevanceScore,omitnil,omitempty" name:"RelevanceScore"`

	// Document content
	// Note: This field may return null, indicating that no valid values can be obtained.
	Document *string `json:"Document,omitnil,omitempty" name:"Document"`
}

// Predefined struct for user
type RunRerankRequestParams struct {
	// Model name, selectable model list: bge-reranker-large, bge-reranker-v2-m3.
	ModelName *string `json:"ModelName,omitnil,omitempty" name:"ModelName"`

	// Query text.
	Query *string `json:"Query,omitnil,omitempty" name:"Query"`

	// List of candidate docs to sort.
	Documents []*string `json:"Documents,omitnil,omitempty" name:"Documents"`

	// Number of top documents returned in sorting order. If not specified, return all candidate docs. If the specified top_n value is larger than the number of input candidate docs, return all docs.
	TopN *int64 `json:"TopN,omitnil,omitempty" name:"TopN"`

	// Whether to return the original document for each sorting result inside the result list. Default value: False.
	ReturnDocuments *bool `json:"ReturnDocuments,omitnil,omitempty" name:"ReturnDocuments"`
}

type RunRerankRequest struct {
	*tchttp.BaseRequest
	
	// Model name, selectable model list: bge-reranker-large, bge-reranker-v2-m3.
	ModelName *string `json:"ModelName,omitnil,omitempty" name:"ModelName"`

	// Query text.
	Query *string `json:"Query,omitnil,omitempty" name:"Query"`

	// List of candidate docs to sort.
	Documents []*string `json:"Documents,omitnil,omitempty" name:"Documents"`

	// Number of top documents returned in sorting order. If not specified, return all candidate docs. If the specified top_n value is larger than the number of input candidate docs, return all docs.
	TopN *int64 `json:"TopN,omitnil,omitempty" name:"TopN"`

	// Whether to return the original document for each sorting result inside the result list. Default value: False.
	ReturnDocuments *bool `json:"ReturnDocuments,omitnil,omitempty" name:"ReturnDocuments"`
}

func (r *RunRerankRequest) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *RunRerankRequest) FromJsonString(s string) error {
	f := make(map[string]interface{})
	if err := json.Unmarshal([]byte(s), &f); err != nil {
		return err
	}
	delete(f, "ModelName")
	delete(f, "Query")
	delete(f, "Documents")
	delete(f, "TopN")
	delete(f, "ReturnDocuments")
	if len(f) > 0 {
		return tcerr.NewTencentCloudSDKError("ClientError.BuildRequestError", "RunRerankRequest has unknown keys!", "")
	}
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type RunRerankResponseParams struct {
	// Output result set.
	Data []*RerankResult `json:"Data,omitnil,omitempty" name:"Data"`

	// token consumption.
	Usage *Usage `json:"Usage,omitnil,omitempty" name:"Usage"`

	// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
	RequestId *string `json:"RequestId,omitnil,omitempty" name:"RequestId"`
}

type RunRerankResponse struct {
	*tchttp.BaseResponse
	Response *RunRerankResponseParams `json:"Response"`
}

func (r *RunRerankResponse) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *RunRerankResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

type Usage struct {
	// Total number of tokens
	// Note: This field may return null, indicating that no valid values can be obtained.
	TotalTokens *int64 `json:"TotalTokens,omitnil,omitempty" name:"TotalTokens"`
}