// Copyright (c) 2017-2025 Tencent. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package v20230901

import (
    tcerr "github.com/tencentcloud/tencentcloud-sdk-go-intl-en/tencentcloud/common/errors"
    tchttp "github.com/tencentcloud/tencentcloud-sdk-go-intl-en/tencentcloud/common/http"
    "github.com/tencentcloud/tencentcloud-sdk-go-intl-en/tencentcloud/common/json"
)

// Predefined struct for user
type Convert3DFormatRequestParams struct {
	// 3D file url address. model file size not greater than 60 mb
	// Supports fbx, obj, and glb format 3d file input
	File3D *string `json:"File3D,omitnil,omitempty" name:"File3D"`

	// Returns the 3D file format. valid values: 
	// STL, USDZ, FBX, MP4, GIF
	// Recommended input models below 50W, may timeout when selecting USDZ, MP4, or GIF format
	// Example value: STL.
	Format *string `json:"Format,omitnil,omitempty" name:"Format"`
}

type Convert3DFormatRequest struct {
	*tchttp.BaseRequest
	
	// 3D file url address. model file size not greater than 60 mb
	// Supports fbx, obj, and glb format 3d file input
	File3D *string `json:"File3D,omitnil,omitempty" name:"File3D"`

	// Returns the 3D file format. valid values: 
	// STL, USDZ, FBX, MP4, GIF
	// Recommended input models below 50W, may timeout when selecting USDZ, MP4, or GIF format
	// Example value: STL.
	Format *string `json:"Format,omitnil,omitempty" name:"Format"`
}

func (r *Convert3DFormatRequest) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *Convert3DFormatRequest) FromJsonString(s string) error {
	f := make(map[string]interface{})
	if err := json.Unmarshal([]byte(s), &f); err != nil {
		return err
	}
	delete(f, "File3D")
	delete(f, "Format")
	if len(f) > 0 {
		return tcerr.NewTencentCloudSDKError("ClientError.BuildRequestError", "Convert3DFormatRequest has unknown keys!", "")
	}
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type Convert3DFormatResponseParams struct {
	// 3D file address
	ResultFile3D *string `json:"ResultFile3D,omitnil,omitempty" name:"ResultFile3D"`

	// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
	RequestId *string `json:"RequestId,omitnil,omitempty" name:"RequestId"`
}

type Convert3DFormatResponse struct {
	*tchttp.BaseResponse
	Response *Convert3DFormatResponseParams `json:"Response"`
}

func (r *Convert3DFormatResponse) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *Convert3DFormatResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type Describe3DSmartTopologyJobRequestParams struct {
	// Task ID.	
	JobId *string `json:"JobId,omitnil,omitempty" name:"JobId"`
}

type Describe3DSmartTopologyJobRequest struct {
	*tchttp.BaseRequest
	
	// Task ID.	
	JobId *string `json:"JobId,omitnil,omitempty" name:"JobId"`
}

func (r *Describe3DSmartTopologyJobRequest) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *Describe3DSmartTopologyJobRequest) FromJsonString(s string) error {
	f := make(map[string]interface{})
	if err := json.Unmarshal([]byte(s), &f); err != nil {
		return err
	}
	delete(f, "JobId")
	if len(f) > 0 {
		return tcerr.NewTencentCloudSDKError("ClientError.BuildRequestError", "Describe3DSmartTopologyJobRequest has unknown keys!", "")
	}
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type Describe3DSmartTopologyJobResponseParams struct {
	// Task status. WAIT: waiting; RUN: running; FAIL: failed; DONE: successful. example value: RUN.	
	Status *string `json:"Status,omitnil,omitempty" name:"Status"`

	// Error code.	
	ErrorCode *string `json:"ErrorCode,omitnil,omitempty" name:"ErrorCode"`

	// Error message.	
	ErrorMessage *string `json:"ErrorMessage,omitnil,omitempty" name:"ErrorMessage"`

	// File generation URL address, with a valid period of 1 day.	
	ResultFile3Ds []*File3D `json:"ResultFile3Ds,omitnil,omitempty" name:"ResultFile3Ds"`

	// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
	RequestId *string `json:"RequestId,omitnil,omitempty" name:"RequestId"`
}

type Describe3DSmartTopologyJobResponse struct {
	*tchttp.BaseResponse
	Response *Describe3DSmartTopologyJobResponseParams `json:"Response"`
}

func (r *Describe3DSmartTopologyJobResponse) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *Describe3DSmartTopologyJobResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

type File3D struct {
	// 3D file format. valid values: GIF, OBJ.
	Type *string `json:"Type,omitnil,omitempty" name:"Type"`

	// Specifies the file Url (valid for 24 hours).
	Url *string `json:"Url,omitnil,omitempty" name:"Url"`

	// Preview image Url.
	PreviewImageUrl *string `json:"PreviewImageUrl,omitnil,omitempty" name:"PreviewImageUrl"`
}

type InputFile3D struct {
	// Specifies the file Url with a valid period of 24 hours.	
	Url *string `json:"Url,omitnil,omitempty" name:"Url"`

	// Specifies the file format.	
	Type *string `json:"Type,omitnil,omitempty" name:"Type"`
}

// Predefined struct for user
type QueryHunyuan3DPartJobRequestParams struct {
	// Task ID
	JobId *string `json:"JobId,omitnil,omitempty" name:"JobId"`
}

type QueryHunyuan3DPartJobRequest struct {
	*tchttp.BaseRequest
	
	// Task ID
	JobId *string `json:"JobId,omitnil,omitempty" name:"JobId"`
}

func (r *QueryHunyuan3DPartJobRequest) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *QueryHunyuan3DPartJobRequest) FromJsonString(s string) error {
	f := make(map[string]interface{})
	if err := json.Unmarshal([]byte(s), &f); err != nil {
		return err
	}
	delete(f, "JobId")
	if len(f) > 0 {
		return tcerr.NewTencentCloudSDKError("ClientError.BuildRequestError", "QueryHunyuan3DPartJobRequest has unknown keys!", "")
	}
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type QueryHunyuan3DPartJobResponseParams struct {
	// Task status:
	// WAIT: waiting
	// RUN: running
	// FAIL: failed
	// DONE: successful
	// Example value: RUN
	Status *string `json:"Status,omitnil,omitempty" name:"Status"`

	// Error code
	ErrorCode *string `json:"ErrorCode,omitnil,omitempty" name:"ErrorCode"`

	// Error message
	ErrorMessage *string `json:"ErrorMessage,omitnil,omitempty" name:"ErrorMessage"`

	// Generates the file URL with a valid period of 1 day
	ResultFile3Ds []*File3D `json:"ResultFile3Ds,omitnil,omitempty" name:"ResultFile3Ds"`

	// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
	RequestId *string `json:"RequestId,omitnil,omitempty" name:"RequestId"`
}

type QueryHunyuan3DPartJobResponse struct {
	*tchttp.BaseResponse
	Response *QueryHunyuan3DPartJobResponseParams `json:"Response"`
}

func (r *QueryHunyuan3DPartJobResponse) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *QueryHunyuan3DPartJobResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type QueryHunyuanTo3DProJobRequestParams struct {
	// Task ID.
	JobId *string `json:"JobId,omitnil,omitempty" name:"JobId"`
}

type QueryHunyuanTo3DProJobRequest struct {
	*tchttp.BaseRequest
	
	// Task ID.
	JobId *string `json:"JobId,omitnil,omitempty" name:"JobId"`
}

func (r *QueryHunyuanTo3DProJobRequest) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *QueryHunyuanTo3DProJobRequest) FromJsonString(s string) error {
	f := make(map[string]interface{})
	if err := json.Unmarshal([]byte(s), &f); err != nil {
		return err
	}
	delete(f, "JobId")
	if len(f) > 0 {
		return tcerr.NewTencentCloudSDKError("ClientError.BuildRequestError", "QueryHunyuanTo3DProJobRequest has unknown keys!", "")
	}
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type QueryHunyuanTo3DProJobResponseParams struct {
	// Task status:
	// WAIT: waiting
	// RUN: running; FAIL: failed
	// DONE: successful
	Status *string `json:"Status,omitnil,omitempty" name:"Status"`

	// Error code
	ErrorCode *string `json:"ErrorCode,omitnil,omitempty" name:"ErrorCode"`

	// Error message
	ErrorMessage *string `json:"ErrorMessage,omitnil,omitempty" name:"ErrorMessage"`

	// Describes the generated 3d file array
	ResultFile3Ds []*File3D `json:"ResultFile3Ds,omitnil,omitempty" name:"ResultFile3Ds"`

	// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
	RequestId *string `json:"RequestId,omitnil,omitempty" name:"RequestId"`
}

type QueryHunyuanTo3DProJobResponse struct {
	*tchttp.BaseResponse
	Response *QueryHunyuanTo3DProJobResponseParams `json:"Response"`
}

func (r *QueryHunyuanTo3DProJobResponse) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *QueryHunyuanTo3DProJobResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type QueryHunyuanTo3DRapidJobRequestParams struct {
	// Task ID.	
	JobId *string `json:"JobId,omitnil,omitempty" name:"JobId"`
}

type QueryHunyuanTo3DRapidJobRequest struct {
	*tchttp.BaseRequest
	
	// Task ID.	
	JobId *string `json:"JobId,omitnil,omitempty" name:"JobId"`
}

func (r *QueryHunyuanTo3DRapidJobRequest) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *QueryHunyuanTo3DRapidJobRequest) FromJsonString(s string) error {
	f := make(map[string]interface{})
	if err := json.Unmarshal([]byte(s), &f); err != nil {
		return err
	}
	delete(f, "JobId")
	if len(f) > 0 {
		return tcerr.NewTencentCloudSDKError("ClientError.BuildRequestError", "QueryHunyuanTo3DRapidJobRequest has unknown keys!", "")
	}
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type QueryHunyuanTo3DRapidJobResponseParams struct {
	// Task status:
	// WAIT: waiting
	// RUN: running
	// FAIL: failed
	// DONE: successful	
	Status *string `json:"Status,omitnil,omitempty" name:"Status"`

	// Error code
	ErrorCode *string `json:"ErrorCode,omitnil,omitempty" name:"ErrorCode"`

	// Error message	
	ErrorMessage *string `json:"ErrorMessage,omitnil,omitempty" name:"ErrorMessage"`

	// Specifies the generated 3D file array
	ResultFile3Ds []*File3D `json:"ResultFile3Ds,omitnil,omitempty" name:"ResultFile3Ds"`

	// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
	RequestId *string `json:"RequestId,omitnil,omitempty" name:"RequestId"`
}

type QueryHunyuanTo3DRapidJobResponse struct {
	*tchttp.BaseResponse
	Response *QueryHunyuanTo3DRapidJobResponseParams `json:"Response"`
}

func (r *QueryHunyuanTo3DRapidJobResponse) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *QueryHunyuanTo3DRapidJobResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type Submit3DSmartTopologyJobRequestParams struct {
	// Source 3D file model link
	// Reference value:glb,obj
	// One of the file formats is required.
	// Url: file size cannot exceed 200MB.
	// 3D model requirements: complex models and topologized models do not support face reduction. recommended input is non-topologized high-poly models, such as those generated by hunyuan 3d. high applicability categories include hard surface, game character, prop, daily objects.
	File3D *InputFile3D `json:"File3D,omitnil,omitempty" name:"File3D"`

	// Polygon type, indicates the model surface is composed of grid components, defaults to triangle
	// Reference value:
	// triangle: triangle face
	// quadrilateral: quadrangle face
	PolygonType *string `json:"PolygonType,omitnil,omitempty" name:"PolygonType"`

	// Reduction level bit type
	// valid values: high, medium, low
	FaceLevel *string `json:"FaceLevel,omitnil,omitempty" name:"FaceLevel"`
}

type Submit3DSmartTopologyJobRequest struct {
	*tchttp.BaseRequest
	
	// Source 3D file model link
	// Reference value:glb,obj
	// One of the file formats is required.
	// Url: file size cannot exceed 200MB.
	// 3D model requirements: complex models and topologized models do not support face reduction. recommended input is non-topologized high-poly models, such as those generated by hunyuan 3d. high applicability categories include hard surface, game character, prop, daily objects.
	File3D *InputFile3D `json:"File3D,omitnil,omitempty" name:"File3D"`

	// Polygon type, indicates the model surface is composed of grid components, defaults to triangle
	// Reference value:
	// triangle: triangle face
	// quadrilateral: quadrangle face
	PolygonType *string `json:"PolygonType,omitnil,omitempty" name:"PolygonType"`

	// Reduction level bit type
	// valid values: high, medium, low
	FaceLevel *string `json:"FaceLevel,omitnil,omitempty" name:"FaceLevel"`
}

func (r *Submit3DSmartTopologyJobRequest) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *Submit3DSmartTopologyJobRequest) FromJsonString(s string) error {
	f := make(map[string]interface{})
	if err := json.Unmarshal([]byte(s), &f); err != nil {
		return err
	}
	delete(f, "File3D")
	delete(f, "PolygonType")
	delete(f, "FaceLevel")
	if len(f) > 0 {
		return tcerr.NewTencentCloudSDKError("ClientError.BuildRequestError", "Submit3DSmartTopologyJobRequest has unknown keys!", "")
	}
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type Submit3DSmartTopologyJobResponseParams struct {
	// Task ID.	
	JobId *string `json:"JobId,omitnil,omitempty" name:"JobId"`

	// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
	RequestId *string `json:"RequestId,omitnil,omitempty" name:"RequestId"`
}

type Submit3DSmartTopologyJobResponse struct {
	*tchttp.BaseResponse
	Response *Submit3DSmartTopologyJobResponseParams `json:"Response"`
}

func (r *Submit3DSmartTopologyJobResponse) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *Submit3DSmartTopologyJobResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type SubmitHunyuan3DPartJobRequestParams struct {
	// Recommends inputting 3D models generated by AIGC
	// Recommended file size not greater than 100MB
	// Face count not greater than 30,000
	// Only supports FBX format
	File *InputFile3D `json:"File,omitnil,omitempty" name:"File"`
}

type SubmitHunyuan3DPartJobRequest struct {
	*tchttp.BaseRequest
	
	// Recommends inputting 3D models generated by AIGC
	// Recommended file size not greater than 100MB
	// Face count not greater than 30,000
	// Only supports FBX format
	File *InputFile3D `json:"File,omitnil,omitempty" name:"File"`
}

func (r *SubmitHunyuan3DPartJobRequest) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *SubmitHunyuan3DPartJobRequest) FromJsonString(s string) error {
	f := make(map[string]interface{})
	if err := json.Unmarshal([]byte(s), &f); err != nil {
		return err
	}
	delete(f, "File")
	if len(f) > 0 {
		return tcerr.NewTencentCloudSDKError("ClientError.BuildRequestError", "SubmitHunyuan3DPartJobRequest has unknown keys!", "")
	}
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type SubmitHunyuan3DPartJobResponseParams struct {
	// Task id (valid period: 24 hours)
	JobId *string `json:"JobId,omitnil,omitempty" name:"JobId"`

	// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
	RequestId *string `json:"RequestId,omitnil,omitempty" name:"RequestId"`
}

type SubmitHunyuan3DPartJobResponse struct {
	*tchttp.BaseResponse
	Response *SubmitHunyuan3DPartJobResponseParams `json:"Response"`
}

func (r *SubmitHunyuan3DPartJobResponse) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *SubmitHunyuan3DPartJobResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type SubmitHunyuanTo3DProJobRequestParams struct {
	// Tencent HY 3D Global model version
	// Defaults to 3.0, with optional choices: 3.0, 3.1
	// When selecting version 3.1, the LowPoly parameter is unavailable
	// Example value:3.0
	Model *string `json:"Model,omitnil,omitempty" name:"Model"`

	// Generates 3D content, describes 3D content.
	// Supports up to 1024 utf-8 characters.
	// Text-To-3D. Specifies either ImageBase64/ImageUrl or Prompt is required. Prompt and ImageBase64/ImageUrl cannot coexist.
	Prompt *string `json:"Prompt,omitnil,omitempty" name:"Prompt"`

	// Enter the Base64 code of the image.
	// Size: specifies the unilateral resolution requirement, not less than 128 and not greater than 5000. size should not exceed 8m (after encoding, it increases by about 30%, recommend actual input image size no more than 6m).
	// Input image suggestion:
	// 1.Simple background (solid-color background) 
	// 2.No text or blended colors
	// 3.Single object
	// 4.The object occupies over 50% of the frame
	// Valid values: jpg, png, jpeg, webp.
	// Specifies either ImageBase64/ImageUrl or Prompt is required. Prompt and ImageBase64/ImageUrl cannot coexist.
	ImageBase64 *string `json:"ImageBase64,omitnil,omitempty" name:"ImageBase64"`

	// Input image Url.
	// Size: specifies the unilateral resolution requirement, not less than 128 and not greater than 5000. size should not exceed 8m (after encoding, it increases by about 30%, recommend actual input image size no more than 6m).
	// Input image suggestion:
	// 1.Simple background (solid-color background) 
	// 2.No text or blended colors
	// 3.Single object
	// 4.The object occupies over 50% of the frame
	// Valid values: jpg, png, jpeg, webp.
	// Specifies either ImageBase64/ImageUrl or Prompt is required. Prompt and ImageBase64/ImageUrl cannot coexist.
	ImageUrl *string `json:"ImageUrl,omitnil,omitempty" name:"ImageUrl"`

	// Multi-Perspective model image. reference value for viewing angle:.
	// left: Left view;
	// right: Right view;
	// back: Rear view;
	// top: Top view (only supported in Model 3.1);
	// bottom: Bottom view (only supported in Model 3.1);
	// left_front: Left front 45 degree view (only supported in Model 3.1);
	// right_front: Right front 45 degree view (only supported in Model 3.1);
	// 
	// Each perspective is limited to one image.
	// Image size limit. the value must not exceed 8 mb after encoding.
	// Image resolution limitation: the unilateral resolution should be less than 5000 and greater than 128.
	// Supported image format: JPG or PNG
	MultiViewImages []*ViewImage `json:"MultiViewImages,omitnil,omitempty" name:"MultiViewImages"`

	// Specifies whether PBR material generation is enabled. default false
	EnablePBR *bool `json:"EnablePBR,omitnil,omitempty" name:"EnablePBR"`

	// Specifies the face count for 3D model generation. default value is 500000.
	// Specifies the supported face count generation range. value range: 40000-1500000
	FaceCount *int64 `json:"FaceCount,omitnil,omitempty" name:"FaceCount"`

	// Generation task type. default: Normal. valid values:
	// Normal: generates a geometric model with textures
	// LowPoly: specifies the model generated after intelligent polygon reduction.
	// Geometry: specifies whether to generate a Geometry model without textures (white model). when this task is selected, the EnablePBR parameter does not take effect
	// Specifies the Sketch for the generative model, allowing input of a Sketch or line drawing. in this mode, both prompt and ImageUrl/ImageBase64 can be entered together
	GenerateType *string `json:"GenerateType,omitnil,omitempty" name:"GenerateType"`

	// This parameter only takes effect when LowPoly mode is selected from GenerateType
	// 
	// Polygon type, indicates the number of sides in the model's surface grid, defaults to triangle. valid values:
	// triangle. specifies the triangular face
	// quadrilateral: mix quadrangle and triangle faces to generate
	PolygonType *string `json:"PolygonType,omitnil,omitempty" name:"PolygonType"`
}

type SubmitHunyuanTo3DProJobRequest struct {
	*tchttp.BaseRequest
	
	// Tencent HY 3D Global model version
	// Defaults to 3.0, with optional choices: 3.0, 3.1
	// When selecting version 3.1, the LowPoly parameter is unavailable
	// Example value:3.0
	Model *string `json:"Model,omitnil,omitempty" name:"Model"`

	// Generates 3D content, describes 3D content.
	// Supports up to 1024 utf-8 characters.
	// Text-To-3D. Specifies either ImageBase64/ImageUrl or Prompt is required. Prompt and ImageBase64/ImageUrl cannot coexist.
	Prompt *string `json:"Prompt,omitnil,omitempty" name:"Prompt"`

	// Enter the Base64 code of the image.
	// Size: specifies the unilateral resolution requirement, not less than 128 and not greater than 5000. size should not exceed 8m (after encoding, it increases by about 30%, recommend actual input image size no more than 6m).
	// Input image suggestion:
	// 1.Simple background (solid-color background) 
	// 2.No text or blended colors
	// 3.Single object
	// 4.The object occupies over 50% of the frame
	// Valid values: jpg, png, jpeg, webp.
	// Specifies either ImageBase64/ImageUrl or Prompt is required. Prompt and ImageBase64/ImageUrl cannot coexist.
	ImageBase64 *string `json:"ImageBase64,omitnil,omitempty" name:"ImageBase64"`

	// Input image Url.
	// Size: specifies the unilateral resolution requirement, not less than 128 and not greater than 5000. size should not exceed 8m (after encoding, it increases by about 30%, recommend actual input image size no more than 6m).
	// Input image suggestion:
	// 1.Simple background (solid-color background) 
	// 2.No text or blended colors
	// 3.Single object
	// 4.The object occupies over 50% of the frame
	// Valid values: jpg, png, jpeg, webp.
	// Specifies either ImageBase64/ImageUrl or Prompt is required. Prompt and ImageBase64/ImageUrl cannot coexist.
	ImageUrl *string `json:"ImageUrl,omitnil,omitempty" name:"ImageUrl"`

	// Multi-Perspective model image. reference value for viewing angle:.
	// left: Left view;
	// right: Right view;
	// back: Rear view;
	// top: Top view (only supported in Model 3.1);
	// bottom: Bottom view (only supported in Model 3.1);
	// left_front: Left front 45 degree view (only supported in Model 3.1);
	// right_front: Right front 45 degree view (only supported in Model 3.1);
	// 
	// Each perspective is limited to one image.
	// Image size limit. the value must not exceed 8 mb after encoding.
	// Image resolution limitation: the unilateral resolution should be less than 5000 and greater than 128.
	// Supported image format: JPG or PNG
	MultiViewImages []*ViewImage `json:"MultiViewImages,omitnil,omitempty" name:"MultiViewImages"`

	// Specifies whether PBR material generation is enabled. default false
	EnablePBR *bool `json:"EnablePBR,omitnil,omitempty" name:"EnablePBR"`

	// Specifies the face count for 3D model generation. default value is 500000.
	// Specifies the supported face count generation range. value range: 40000-1500000
	FaceCount *int64 `json:"FaceCount,omitnil,omitempty" name:"FaceCount"`

	// Generation task type. default: Normal. valid values:
	// Normal: generates a geometric model with textures
	// LowPoly: specifies the model generated after intelligent polygon reduction.
	// Geometry: specifies whether to generate a Geometry model without textures (white model). when this task is selected, the EnablePBR parameter does not take effect
	// Specifies the Sketch for the generative model, allowing input of a Sketch or line drawing. in this mode, both prompt and ImageUrl/ImageBase64 can be entered together
	GenerateType *string `json:"GenerateType,omitnil,omitempty" name:"GenerateType"`

	// This parameter only takes effect when LowPoly mode is selected from GenerateType
	// 
	// Polygon type, indicates the number of sides in the model's surface grid, defaults to triangle. valid values:
	// triangle. specifies the triangular face
	// quadrilateral: mix quadrangle and triangle faces to generate
	PolygonType *string `json:"PolygonType,omitnil,omitempty" name:"PolygonType"`
}

func (r *SubmitHunyuanTo3DProJobRequest) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *SubmitHunyuanTo3DProJobRequest) FromJsonString(s string) error {
	f := make(map[string]interface{})
	if err := json.Unmarshal([]byte(s), &f); err != nil {
		return err
	}
	delete(f, "Model")
	delete(f, "Prompt")
	delete(f, "ImageBase64")
	delete(f, "ImageUrl")
	delete(f, "MultiViewImages")
	delete(f, "EnablePBR")
	delete(f, "FaceCount")
	delete(f, "GenerateType")
	delete(f, "PolygonType")
	if len(f) > 0 {
		return tcerr.NewTencentCloudSDKError("ClientError.BuildRequestError", "SubmitHunyuanTo3DProJobRequest has unknown keys!", "")
	}
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type SubmitHunyuanTo3DProJobResponseParams struct {
	// Task ID (valid period: 24 hours).
	JobId *string `json:"JobId,omitnil,omitempty" name:"JobId"`

	// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
	RequestId *string `json:"RequestId,omitnil,omitempty" name:"RequestId"`
}

type SubmitHunyuanTo3DProJobResponse struct {
	*tchttp.BaseResponse
	Response *SubmitHunyuanTo3DProJobResponseParams `json:"Response"`
}

func (r *SubmitHunyuanTo3DProJobResponse) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *SubmitHunyuanTo3DProJobResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type SubmitHunyuanTo3DRapidJobRequestParams struct {
	// Text-To-3D, description of 3D content, forward Prompt content
	// Supports up to 200 utf-8 characters
	// Either ImageBase64, ImageUrl, or Prompt is required, and Prompt cannot coexist with ImageBase64/ImageUrl
	Prompt *string `json:"Prompt,omitnil,omitempty" name:"Prompt"`

	// Input image Base64 data
	// Size: unilateral resolution requirement not less than 128, not greater than 5000, size not greater than 6mb (after encoding, size increases by approximately 30%). format:
	// jpg, png, jpeg, webp
	// Imagebase64, imageurl, and Prompt are required, but Prompt and imagebase64/imageurl cannot coexist
	ImageBase64 *string `json:"ImageBase64,omitnil,omitempty" name:"ImageBase64"`

	// Input image Url size: 
	// Unilateral resolution requirement not less than 128, not greater than 5000. size not greater than 8mb
	// Format: jpg, png, jpeg, webp
	// Imagebase64, imageurl, and Prompt are required, and Prompt cannot coexist with imagebase64/imageurl	
	ImageUrl *string `json:"ImageUrl,omitnil,omitempty" name:"ImageUrl"`

	// Specifies whether PBR material generation is enabled, false by default.	
	EnablePBR *bool `json:"EnablePBR,omitnil,omitempty" name:"EnablePBR"`

	// Specifies whether to enable the single geometry generation option
	// When enabled, it generates a 3D model without textures (white model)
	// When enabled, the generative model does not support OBJ format
	// Default model file format is GLB
	EnableGeometry *bool `json:"EnableGeometry,omitnil,omitempty" name:"EnableGeometry"`
}

type SubmitHunyuanTo3DRapidJobRequest struct {
	*tchttp.BaseRequest
	
	// Text-To-3D, description of 3D content, forward Prompt content
	// Supports up to 200 utf-8 characters
	// Either ImageBase64, ImageUrl, or Prompt is required, and Prompt cannot coexist with ImageBase64/ImageUrl
	Prompt *string `json:"Prompt,omitnil,omitempty" name:"Prompt"`

	// Input image Base64 data
	// Size: unilateral resolution requirement not less than 128, not greater than 5000, size not greater than 6mb (after encoding, size increases by approximately 30%). format:
	// jpg, png, jpeg, webp
	// Imagebase64, imageurl, and Prompt are required, but Prompt and imagebase64/imageurl cannot coexist
	ImageBase64 *string `json:"ImageBase64,omitnil,omitempty" name:"ImageBase64"`

	// Input image Url size: 
	// Unilateral resolution requirement not less than 128, not greater than 5000. size not greater than 8mb
	// Format: jpg, png, jpeg, webp
	// Imagebase64, imageurl, and Prompt are required, and Prompt cannot coexist with imagebase64/imageurl	
	ImageUrl *string `json:"ImageUrl,omitnil,omitempty" name:"ImageUrl"`

	// Specifies whether PBR material generation is enabled, false by default.	
	EnablePBR *bool `json:"EnablePBR,omitnil,omitempty" name:"EnablePBR"`

	// Specifies whether to enable the single geometry generation option
	// When enabled, it generates a 3D model without textures (white model)
	// When enabled, the generative model does not support OBJ format
	// Default model file format is GLB
	EnableGeometry *bool `json:"EnableGeometry,omitnil,omitempty" name:"EnableGeometry"`
}

func (r *SubmitHunyuanTo3DRapidJobRequest) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *SubmitHunyuanTo3DRapidJobRequest) FromJsonString(s string) error {
	f := make(map[string]interface{})
	if err := json.Unmarshal([]byte(s), &f); err != nil {
		return err
	}
	delete(f, "Prompt")
	delete(f, "ImageBase64")
	delete(f, "ImageUrl")
	delete(f, "EnablePBR")
	delete(f, "EnableGeometry")
	if len(f) > 0 {
		return tcerr.NewTencentCloudSDKError("ClientError.BuildRequestError", "SubmitHunyuanTo3DRapidJobRequest has unknown keys!", "")
	}
	return json.Unmarshal([]byte(s), &r)
}

// Predefined struct for user
type SubmitHunyuanTo3DRapidJobResponseParams struct {
	// Task ID (valid period: 24 hours)
	JobId *string `json:"JobId,omitnil,omitempty" name:"JobId"`

	// The unique request ID, generated by the server, will be returned for every request (if the request fails to reach the server for other reasons, the request will not obtain a RequestId). RequestId is required for locating a problem.
	RequestId *string `json:"RequestId,omitnil,omitempty" name:"RequestId"`
}

type SubmitHunyuanTo3DRapidJobResponse struct {
	*tchttp.BaseResponse
	Response *SubmitHunyuanTo3DRapidJobResponseParams `json:"Response"`
}

func (r *SubmitHunyuanTo3DRapidJobResponse) ToJsonString() string {
    b, _ := json.Marshal(r)
    return string(b)
}

// FromJsonString It is highly **NOT** recommended to use this function
// because it has no param check, nor strict type check
func (r *SubmitHunyuanTo3DRapidJobResponse) FromJsonString(s string) error {
	return json.Unmarshal([]byte(s), &r)
}

type ViewImage struct {
	// Specifies the viewing angle type.
	// Valid values: back, left, right.
	ViewType *string `json:"ViewType,omitnil,omitempty" name:"ViewType"`

	// Image Url.
	ViewImageUrl *string `json:"ViewImageUrl,omitnil,omitempty" name:"ViewImageUrl"`

	// base64 address of the image.
	ViewImageBase64 *string `json:"ViewImageBase64,omitnil,omitempty" name:"ViewImageBase64"`
}